{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pocovidnet.evaluate_covid19 import Evaluator\n",
    "from pocovidnet.evaluate_video import VideoEvaluator\n",
    "import os\n",
    "from pathlib import Path\n",
    "\n",
    "\n",
    "# if we're in the notebooks directory, go up by one\n",
    "if os.getcwd().find('notebooks') != -1:\n",
    "    os.chdir('..')\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1ac6e6f60> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1ac6e6240>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe0ca4e9cc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe427bdd0f0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdfd6be8e80> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe12ab66470>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe3f19e49b0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1541cbcc0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe12f4cd748> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1d84d1f60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    }
   ],
   "source": [
    "ve = VideoEvaluator(\n",
    "        weights_dir=\"trained_models\",\n",
    "        ensemble=True,\n",
    "        split=0,\n",
    "        model_id='vgg_cam',\n",
    "        num_classes=4\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "video_path = '../data/pocus_videos/convex/Cov-grep-7511.mp4'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "_ = ve(video_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pred class: 0 \n",
      "frames above threshold [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17\n",
      "  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35\n",
      "  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53\n",
      "  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71\n",
      "  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89\n",
      "  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107\n",
      " 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125\n",
      " 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143\n",
      " 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161\n",
      " 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179\n",
      " 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197\n",
      " 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215\n",
      " 216 217 218 219 220 221 222 223]\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1824fc358> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe12e00afd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe235973ef0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2359739e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1afd54518> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1afd58eb8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd106bbc88> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd106bff98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe237418940> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd11fe8f98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe237388ef0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2373889e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd183a9e10> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd183a9860>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1dd29cd68> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1dd29cda0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd128a6c50> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd12897f60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe278659ba8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe278659be0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd129b2828> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd18359e80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd12a95198> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd12bdeba8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2785d7668> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2785e1cc0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c1b68da0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c1b68dd8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe068ea5898> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe4200890f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1288c2b0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe157e59048>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd105aecc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd105aec18>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd11f07e10> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd11f07a20>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a261ba58> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27ae5e780>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd12725b38> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd180daf98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd105c5748> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd12886da0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd12a10eb8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd12a107f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd18f2ada0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd18f2a7f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a1703f98> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a1703470>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27ad48978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27ad58fd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd30e27748> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c18f1c50>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd12b7ceb8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd12b7c7f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1ffa75588> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1ffa52f28>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd11236cf8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd11236710>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1b831c50> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1b831c88>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd32403f28> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd32403a58>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c550e6a0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1bbfdcf8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27fbaee10> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27fbae828>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd105d5fd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd11373e10>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1109ec88> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1109ed30>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe157ff0860> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1dd289f98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe0a5500978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a06e9940>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2786719e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd12ae94e0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1dd66eb00> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1dd66eeb8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2315975c0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2315974a8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c5526ba8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c5526be0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a16c8ef0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd11fe9198>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1ff727978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1ff7279b0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1ddd8e5f8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd180e7978>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c2670cc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c2670cf8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a16a6828> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1909f4e0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a3ea5f98> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a3ea5ac8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1b963710> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1b971d68>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd141f1dd8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd141f1e10>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1370ddd8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd137169e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a4a44ba8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a4a44be0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddc814d828> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddc8129e80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd11395518> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a49cdeb8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd137420b8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd34436358>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd11236438> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1dc8d96d8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe12ffd5668> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a25fa160>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd3588eeb8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd3588ee48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1ff716a58> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1d84d1e48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a4a334a8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1b971908>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdfa00220b8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdfa00229b0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd30e96080> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a26222e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c18f72b0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c18f77f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1909b7b8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1cb6be10>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1b8caf28> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1b8ca860>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1bba9e80> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1bba9eb8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c6f41c18> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c6f09f28>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddaa90ab70> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddaa90aba8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1e25b7f0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdda906ee48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddcc015fd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddcc015898>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a5667c50> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a566bf60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd8233c898> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd82347ef0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27fd234a8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1d6b0518>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1dae70f0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd34656eb8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27d901940> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27d901710>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd12bde7f0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd18f2df60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1b952438> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a4bae048>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27f38e9e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27f38ec18>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27d8ea2e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd34454048>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd3588e6a0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1fa99c438>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a3e84748> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27e492da0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdda9137eb8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdda91377f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1e1c5e10> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1e1c5e48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd84a14ba8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd84a28eb8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddca0defd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddca0deb38>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1cfea780> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1cff6dd8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd85376ef0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd85376828>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd872dce48> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd872dce80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd87d76be0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd87d63ef0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c7fddb38> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c7fddb70>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde189aafd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd872a7c88>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde18979f28> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde18979630>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddaac9a9e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddaac9a550>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27d875898> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27d875f60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c55264e0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe1555343c8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1cb5fe48> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1cb5fc50>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1b8eaa58> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdda8ef8b00>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd34656898> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe27d88dcf8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1ff6714e0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1bb46e80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c7e5cc50> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c7e7df60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c7ef5ba8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c7ef5be0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2e86b3828> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd8748be80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde20a432e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde20a438d0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddc818c748> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddc818c4e0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddce31ed30> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddce30a9b0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddce2a59b0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddcfdd1fd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2eb3776a0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2eb34ccf8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde217a2e10> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde217a2828>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde22ee4d68> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde22ee4da0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27d864a58> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddad0c09e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddadd33128> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f9436a20>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd853b3080> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c7fca390>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe27fb0af28> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1cbc54e0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd871bbcc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde20a83c18>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f9372f60> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f9372dd8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddce2a5c50> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddcfdd1cc0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddc818fb70> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd871b0fd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddad0cff98> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddad0cfac8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2eb4868d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddaa515a58>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fa1e6e48> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fa1e6e80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fa2f9be0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fa2feef0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddce3c6b38> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddce3c6b70>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddaeefb978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde1b565dd8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde20c6d518> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddce43ceb8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde1c32dc88> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde1c32af98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f2483be0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f2483c18>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fa432860> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fa42a780>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f3d075c0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f3d38f60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd351be2e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde2316afd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddce443278> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddce417470>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f1404f60> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f1404048>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c6e8d470> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1da82d30>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddce8205f8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddce8a57b8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd11231b38> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1b90d748>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde22e8ab70> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde22e8ac88>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddc8170470> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddce8423c8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddaee3df28> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddaee3d940>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddce41a588> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddced58f28>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fa4cd710> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fa4cd160>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddaf42e9b0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddaf43afd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2ef1baf28> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2ef1ba3c8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde1c1f36a0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2eff9bcf8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde1cda4e10> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde1cda4828>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb80c9dba8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb80c85e80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde1f69afd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde1f69ab00>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f3ed2cc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f3ed2978>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde24de32e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde24de38d0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb8140c048> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb92fd2e80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd87ad3f28> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd87aeb160>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1e25b128> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd1e25bf60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe1dfdae9b0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fa3f8240>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd351924e0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd35192400>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd136d20b8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdd136d26a0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2c7e0a8d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde1b572860>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb825223c8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb82522080>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2a4ad9cc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2a4ad96d8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde23c73c18> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde23c73c50>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb9306c978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb9306c9b0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f566d5f8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f5691978>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde26c24cc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde26c24cf8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde26c4b940> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb917e5f98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f56a6ef0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f56a69e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde26d8fe80> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde26d7ee80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fe9dee80> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fe9de7b8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb8567fbe0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb85683ef0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2ef1a0630> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f2b4bb70>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe16ef16198> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe16ef16d30>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddaa2edcc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fddaa2ed6d8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fddccd08d68> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2eb3bb128>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fa6266a0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fa626f60>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd87304c18> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2c7ebbf28>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb60aff080> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb60aff6d8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fa4f3828> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fa23be80>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde22e2a2e8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde22e2a8d0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f453d748> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f453d4e0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde26ba5c88> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde26b91f98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde26ed0940> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb83bb9f98>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde26f49ef0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde26f499e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f312bda0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f312b7b8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f316fcf8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f316fd30>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb23e45978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb86cd5fd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fde26e89748> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb86c78c50>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb61c37eb8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb61c377f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb969b8e10> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb969b8e48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb86cd9128> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb86cd9b00>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fc101c88> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde26d75358>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd183ae1d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2ee955da0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f5636cc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f5636048>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f41cd518> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f41cd0f0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb60f81898> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb60f817b8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fc0dfa58> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fde231e5630>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f4535da0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f4535dd8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f3174da0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f7ded9b0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb628bab70> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb628baba8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2ffe187f0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2ffe2ae48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb63294eb8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb63294ef0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb6170bc50> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb616e2588>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb0260ac88> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb0260acc0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdab2a05908> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdab2a10f60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb6394f5f8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb6391f978>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb97f31550> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb97f19b00>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdab1e7dda0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdab1e7ddd8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdab1e54828> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdab1e54320>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb22156e80> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb23fc5a20>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb964e7dd8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb23bc0e48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdd1cff6978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb9304c080>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb87e3add8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb96676fd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb8140c898> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2f2066f60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2fe686940> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2fe686208>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb8326bb70> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdab1e9ffd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f5e8c7f0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb60b2efd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb87e50ac8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb61ba3e48>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb6173b780> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb6173bfd0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2e804ed30> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fe2e804e748>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb97fe4c88> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb97fe4cc0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdae3c27908> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdae3c34f60>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdab1d49978> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdab1d499b0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb03e4e5f8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb03e5b978>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb03fc1d68> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb03fc17b8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdae40a7cc0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdae40a7cf8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdae4313ef0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdae43139e8>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdae4496550> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdae42ed390>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb26b29048> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb26b29f28>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fdb63248e48> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb02646198>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7fe2f7cad7b8> and <tensorflow.python.keras.layers.core.Dropout object at 0x7fdb61799be0>).\n",
      "Model restored. Class mappings are ['covid', 'pneumonia', 'regular', 'uninformative']\n"
     ]
    }
   ],
   "source": [
    "img = ve.cam_important_frames(save_video_path='aaa',\n",
    "        uncertainty_method='epistemic', cam_dims=(1000,1000))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.image.AxesImage at 0x7f8a1b9fdac8>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAQEAAAD8CAYAAAB3lxGOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+j8jraAAAgAElEQVR4nOy9S4xlW5oe9K39Pq+IExGZN++jblZVF+Wm1WKALNkDT1ogJDAWPQG7MbJsy1JNsAQChNuMGIBkJkBLSEYlNZIbIRVPyR60hBCoBy0BMm0sIaopu1xd1XVvZWVmvM57vxeDfb51vrNyn4jMm5G3IqtiSZGRsc8+e6+91v/4/u//19rGWouH9tAe2i9uC37WHXhoD+2h/WzbgxF4aA/tF7w9GIGH9tB+wduDEXhoD+0XvD0YgYf20H7B24MReGgP7Re8vRMjYIz5F40x3zPGfN8Y85vv4h4P7aE9tLtp5q7rBIwxIYB/BOBfAPAZgL8P4F+31n73Tm/00B7aQ7uT9i6QwJ8C8H1r7Q+stSWA7wD49Xdwn4f20B7aHbToHVzzEwA/lr8/A/Cn/ZOMMd8C8K3tn3/yHfTjrdpoABgAIFDq+33TZ9rMDT/yeVl1Pw/tob2jdm6tfewffBdG4LWatfbbAL4NAMYYq6DEwHh6JBpn3AW+0H2NMQjDEMPhENZaFEWBqqqgYVEYAv/MnwAyAKgBNNuf1vt92zGLboRDAPH2/7H3/2j380fPgB99/oUe66H9HLY4jjEejzEcDrFerzGbzdC27SvnGWN6vr1rIts/6vv8XRiBzwF8Kn9/ZXvslrZ7kFcNwCunwJjb7UDf4BhjcHx8jI8//hhZlmE2m+Hy8hLL5RJlWfYO8ite2z/20B7aHTVjDOI4xtHRET744AP88i//Mr7+9a/je9/7Hn7/938fs9nslfPftr0LI/D3AXzTGPN1dMr/GwD+4m1fMsbAvoKj+aH7Z/unBezNhuDQ4NC6ZlmG09NTfOUrX8FiscCzZ89wcXGB5XKJqtrAmEbuZ6Qfe12BNfbBGDy0t27GGGRZhpOTE3zyySf41V/9VTx9+hRpmiIMQ1hr8eMf/xjf/e530TTN7Rd8g3bnRsBaWxtj/jqA/xkdEP6vrLX/783fOuRWbXfc7hTNmN1hGoL968hf2w8Jh8IwxGg0QpZlaJoGm80GURTh6OgIw+EQH330Ea6urnD+8qcYjq5higJNfWDAt12mgThowB7aQzvQjDEIggCDwQDT6RRPnz7Fr/zKr+Dp06cYDoeo6xplWWK1WqGua5ycnGAymWA2m+Eus3rvhBOw1v4ugN99k+8YY7Zeve/hzFbx7WHyred6/t/D4RDT6RRpmsIYg6IoEAQB2rZFFEUYjUYYjUY4PT3CL318idXFBRaXC2xWG1R55bqy65XpkIB08wEVPLTXaWEYOsj/6aef4pvf/CY++eQTZFmGKIqc8s/nc8znc1xeXqIoCoxGI6zXa5Rl6QzB24YEPzNi8PbWbwzs9rPex956ZmvtnqU0xiCKIkwmE6RpiiAIEAQdEVmWJYIgQF3XMMZ0MVkU48mTJ0gePcZ6vsbL5y8xu5xhs9qgWBeobd2Rf969D3b7oT00AEEQIE1TjMdjnJ2d4Rvf+Aa++c1v4vj4GEmSIAxD1HWNoiiwWq1wcXGB8/NzXFxc4OrqCpvNBkmSYDAYvEJmA/jC6ODeGIHX6j7DABhYhgXbg0zn9cFyYwySJEEQBGiaBtZaRFGEKIr2rGjbtt1AhoC1AaI4wunpKU6PT1GXNa4vrvHipy9wfXmN9WKNuqi77xCh9D3E6x6DH9o8tJ+HRsifZRnOzs7w8ccf4+nTp3j69CmOjo62CNiiLEvUdY3NZoPZbIbz83NcX187sno0GuH4+BjWWiRJgrIssV6v76SP98YIMDH4qkO13t/+Ccb9qTpkrd159jhGHMdomgZVVSGOY1hrEccxsixzxMtms0Fd14hCwDYGZd2gqitEJkIap/jq06/ia1/5Gi5eXuD8+TlmVzPMLmdYzpco6y08s+hQAn8HePUYf+uPBR6dAJ//FKjquxjPh/azbAw/h8MhJpMJnjx5gm984xuYTqfO6y+XSzRN47z/er3GxcUF5vM51us1giDAcDjEaDRCkiQAgKqqEAQBFosFiqK4E5LwHhkB7HjAvkqcm9yk7TcU9PiTyQRZlrljVVVhPp+jqio0TYPJZOLCg7qukYwtmsqiKAOgBkxrUMc14kmM0WCEr376VXzj6TewWqzw7LNn+PyPP8f5i3OsF2tslhu0tgVawG7rBUyAfYVv0BkH/t4eH6XAh4+BHz97y3F8aD+TRsQ5Go0wHA5xdnaGs7MzHB8fYzKZIEkSrFYrXF9fO9lr2xZFUSDPcxRFgc1mAwAYDAYufI2iTk3btkUQBM7ApGnqzn+bdn+MQNsC23i+a69RHHRLDGSMwWAwwPHxMYbDoTseBAGqqsJiscBms8F8PkcURWjbFnVd4+zYYjFvYQqDGDFChLCVxXV1jWbYYDwcI41SJGGCj558hEk2wezxDOfPz3H58hKb1Qar+Qp5XgCt3Vd6g30DIL+NAb7yIXB+BWzyLzqQD+3Lbsw6jUYjTKdTPHnyBKPRCGEYAugcz3w+R9u2yPMceZ47WSMSaJoGxhikaeqMSJZliOMYxhiUZYnNZoPVaoXFYoH1en1nqcL7YwTQ1QkYn3ETW2DfMGaO4xjD4RBxHCNJEqRpiuFwiPF4jLIscX5+jqurK6xWK2eVjQE+fhRhOQ8QNzFMbJBmKWxjMV/NUa5KVOMKaZSiKRs0VQNbWwySAT568hGenD7BernGxcUV1psNqrLAcrNAXuWobQ3b2n5EsDUOSQR89RPgez/4wkWRD+0dNxJ8WZYhTVOkaYqzszNMp1MXXgIdqqSCk28qigJlWTrlZ3EaUcRgMHAZAhLWVVU5BLFarVzWoK7vJm68R0bAbrn/GyRfP7rFIARBgJOTE5ydnSFJEsRxjMFggEePHnXMf5Lg+fPn+OEPf4hnz55hNpt18ZaxaOsAm1WEuq0RD2IEWYAwDNGgwWq5Qlu2GCQD2NrCNhaBDWCsgWkMAgSYTI4xOT5BGEWoiwKXl+e4Xl5jvpljVaxQtF2GwVr7SphgAuCDE+DFMXB5/daD+tDuqEVR5OLz4XCIwWDgHEoYhg6mW2uR5/me4nfOpRNYIgAaAGX027ZFVVUu1l+tVsjz3Cn+arXCZrNxhgSAu+dbPdtbffvOWseUdcN0iBpUChDbTEB/M8ZgNBrhww8/xOnpqSMBx+MxTk5O8PjxY4zHYxwfHyNNUyRJgmfPnqEoCmQp8NETwG5KtOsWVVFhtVxhkAxQFRXKvERkI4Rt2Cl+29UwmNZ0SowAJjSAMWiaBmEY4vHjD/Dog0dYFStcr66xzJdYFkuUTYmiLVDaEq1tnVEIAuDrnwKzBXDHxWEP7TUaFZbensz8ZDLBZDLBcDhEnudOEYFdes5ai6ZpUJalY/aZog7D0H1WVZVDAW3bOtK6LEuXtWKxEDmDPM8dl0Di27//F2n3xAgAh3Nsb56CT9MUH374IZ48ebKXhkmSBFEUIY5jjEYjpGnq6gMGgwHW6zVOpwF+6WsN1lcrbC43qDc1qrxCW7QoNyXasoUtLeqoRogQcRgjaAO0dYsAAcI4YTEjbNsitLZbQxQAg3SAJEtwak5RtiXW1RqrYoVNtUFe58jrHLWp0QYtjoY1pkctLq7eemAf2ms0evPhcIijoyMnI3Qco9HIQfOmaRycB+AUnEpOkm+9XjuPz5Q0FZ3FPtZahwx4DaAzRH7IwOMscLurqsF7YwQ0Pci2owhf/2E7z/sYH3/8MY6OjnB8fIwsy5yFbtsWi8UCQdBB/CRJcHJyAmMMlsslTo42GKQ5zAAIRyHqoEZTNig3JaIgQmlLLOdLLOqFSx2a1sDWFkEYIRuNkAwGCLcFSc60WcB03CdggDRKkQ5STMMpatQo2gLrco3KVihtiU21wZ/4pQ3+4XdLNE3bWxzyi9b8MvC3uU4QBI4zmkwmGAwG7u+TkxNXVEYv3rbtnvJSOenFeb2maZznXq/XyPPcKThZfiq9jx50jpne1pJ3IgRFEWw/N0igp8znwJmH23A4xOPHj53ykxTkRDLuWi6XLl3Ytq2L7UbZlripGoQmRJzGQAhUQYUQIepBjUWwwHq5RlM2WG1WqMsa1gJBFCOta6RVhWw0QjYYILAWdrt8uVtrZGAbi9a2iKOO+YUBTGgwHA8RJAHaoEUTNPj4aQkb5Xh5vnJwkPEmf/zqyJ/n9kXhLw0+60JGoxEGgwHSNMXx8TFOTk6QZZkj4gi1qeyM0WkA2I8wDJ08+QU/Ol80AmT6SRZaa53xSNPUGQIqOCtbufydz80fooGfE07Aj/t3R23POYdaFHUVfpxUxnCEepzALMswGAxQ17Ub6G5SWnz05AhRBZS2RGlLVOsKrWmRpRmyKEM8iXEyOUG+zFGsC6wXa+SbAnXbompb5GWJZVEgWq8xHI+RRhGyKALSFFkUIYojREmEMA0RD2IgBjbVBptygzjoipqCNECURfggC4EY+MN/vHbeZbPZOHKoKArnVdQ43CVUvA+NXlGRwCFCjMw9FZ5ZoTAMXXZI8+9xHCOKoj2kqB66qqq9nL5WmlZVt55EyTwNGdq2dfenMwqCwKEEFrKRbKzr2qX/aCDYqPQajvzchQO3Pc5tnxtjcHR05HK0cRw7uD8ej5EkiZtgCgQtf1mWW6InxNlJheK6BGKgMQ3yOkdTNggRokWLMA0xHA9xOj6FaQ3Wyw3yskTdtlgVBS5nMyw3G5R1jcVqhY0xyKIIdZZhlKYYZSmyOMPR+AjZJEOQBNhUG6yKFWxkkY0yhFmIIAlQBzU+fNTgs2ddYch0OkXTNFiv19hsNi7VVFUVNpsNqqpy5JFCTo0r1ZO8D42ekl6XHA6VnfE4M0BU9CiKMBgMkCSJq7ZTY2KMcUpF78vfQRA4ZVeIz3UmcRyjrms3D9yYxg8NmD1gP+ls1us1VquVy1jxcxp4RayUWRq9uzYAwD0yAmxf9NHiOHZLLRk/0fuzqIIFGPQoURQ5I5BlGQIzwtkpcLUpUJmqI/oQorENqrJCkzfdT9ogizMM0gEmR0cYtC1qAKOmweTkBHldY1OWWG02aIoCobVA02C92aAuyy71mMYIogCmMTCBwTAbwsQGg9EA6SiFDS1W1QrjwQanJwEurgJX3qxeiR5iMpk4L6SsMoWGTeErACfAAPYErXdzFdxNPH7oOJWb/QiCwHnSNE33zqPih2G4l6+nZ6cX5f388InHiQRVwejpaXTW67XbeIbem4U/RVEAgOsH04g0Riwa4n2rqkKWZTg+Pnb3YSEQUYAiCTUCHP9Dc/NF270zAm/SFCImSQJjDNbrNdI03YNiQRCgKAqXIRiNRk7YKABBEGA4iPHhB48xNimW2RLr0RrLqyWWsyUuX15ivVijXJVYYokIEQbZEHGaIkxTxFmGOE2RjsdAGKJsGhRlCbPNENR5jsXVFdbzOdarDRrbYL6YAzEQJAHSUYrBZIAkTWBTi6ZttguUanz02GCximFM11fGr4xB6YGUxMqyzKWi+HxUDP6tKIGKx4KWvhVqjI/ViPjn+dBdjzPlxviWQs7GsM2/bhRFe/BdPTkAN8dUNoZ5Sq5pqKR94j1ZoKOkHg0pi3OKonDGRwt7kiRxYQZDTRoLopCyLN3uVURo5BnW6zWWy6WrA+DnfmjSN9530d57I0DBGAwGaNsW8/ncWU56BsK7oihwfd1V4FBwALiwII0bJHGM48kxRmaEMi1RTApslhucjE+6RUMXMyxnSxRlgdU6RxBFiLIM6XCIZDBwv4M4xnAyQRKGSIIAQdtiMhrh6vwcm/kcVVlg3ayBGDCxwTpfY52vUVQFsjxDYxpsqg3qsMZgkGCQxmiROLjKlWSaj/Z/uC6dsJJCTwgN7LPOFDotRGHT3HefVwrD0F3fh90cYyqIKitDGiW79NoKz1Wp9TwuquFaEQB7S8MB7HlV/ihCpEIHQYDlculW8LGPWq8/Go1wdnaG4XC4dw0SjgAcIuP/F4sFzs/PtztX7ZAXsw4M4xT6+7zHuwrj3lsjoLCQBT+s1qJnLIoC8/kcjx49wnQ6RRzHbnI0liSKyFJ0tf4WCE2INE4RDkIMogGOBkc4OzrD5fQSFy8usFissC4K5FWFvCyxqWuY9RrJeu2MwXA8RjQcwmwVbTKdIk0SlNMpNssF1vnKbTK6KlZYXC+wWq8QpiHasO1qBqIW8ThGYHNczceIonhPkBl/Mh6mEpOVpqchs62owSee+DmV1B9vxsnqybUPVFZFWaqI6snZT35fQxlFLj6811p7NvX86n0Z+iha0jFgMVcURa62XxGGckqUNe4CxBR0nue4vr7uFp5tZYkE7nK5dPX+rPmn0QOw90w0YCQc2T9FaO+qvbdGANjle+kFqqpynogEi6ZqhsPhHl/AhR9HR0cdsRTtBMVujUGwrQCMsxjJaYJJNsGj6WOs8xzLzQaXsxkurq+xWK87g9A0CIoCSVFgXZaoyhLT8RjjNEUUhhiNxzgajVCNx1gu50AEmMRgtpzhYnaBvMpRtRVMbIAYsIFFvskRBw2uLgvESeYEHtix4axos9ZiNps5pdIQQXPbrKJkUQp/UxH0bzaOra+EvoHoCwmofPSqRAIkNtlfekPG+zQcLJDRsluf5KOicGWejzS08fnjOAYAF9vT6EynU4cmmWJmf8bjMU5PTx2/RAi/Wq2wXC734D0hvmYZOF50PhxDji2NSFEUdx7/97X32giwEdpxohkGKKtMhKBeJgzDPcNR1QmSNIRtLOqyBmogCiPY2qLclAjCANkwQ5ZkmLYWZdPg0WaDi+trPHvxAleLBdZFgaKusVmtsN5ssLy+xmI4xHQ8xtFwiKNtUUqWpjDBBMkwQTJMMFgNEA0irMs1EAFRFgFxV5+waTY4XxZo5TnJfo9GI0wmExwfH7utp5bLpVMWQk9g50XpWRRiA/vKrN5ZiSk2nstsC1Nyeh7Hm/dVL0jYThjMNFvbtm7eGK8rwiEvoeldRQBEe/P5fA9p0JgwTce1AAwL+RxURDaO82AwcKtPSeaxKpC8weXlpUvVcuzIoRhjHBdFDoH7WgDYc2QMR7SegHL+Ltp7bQSU7FJGWQtCuMSTk02CJs+7tboXFxeYzWb46KOPcHI0Rf3BtgIQnZJkUQY0QFu3WKwWaMouMxCFIYIoQpwkHTkYxzharZDXNZabDebLJdZ5jnZrEFBVqNZr4OgIbZahKUsUVY6xGSNIA6RZipPTEwzqAdqwRZRGsJHtOIF2gFm5QBxbpxyDwcBtkDqdTnF6eorhcIgkSTCfz51A0+NSoOiJNEvAMWQoAGCvuMpn0OmpWeBC9ECPrcLK9OViscByuXQK5sf2LLcFuvhajTQNGQk7GgH2k6EguSEaOhoRP8tAJZxOp279CBtDSMbuTOnVde1QA8lThl3r9RpXV1e4vLxEVVUOxZBHSJIEk8nEIc7JZILxeAwADjmoQeGzLpfLu1aZ3vbeGgFObLwtBCFUI8FDzzQej50VB3ZZBAod4dpyuURTf4CvP/kQx9kEabYlDi1grEGSJYjTGGVRYr1ZIzIRkjRDGEUYD4cI4xindY3aWhRNg+Vmg8VqhXKzAeq6Wz9gLaIgwGa9xma1RNEUKFEib3KYxMCGFibYkndxhGgQIRyEyG2O0cJiONzFsCcnJ/jwww/3Mhxk9cnC07OSJKR3p9Kyjl1XwdFj85pUJsbZwA55+ctiqSgK06uqcnlxzTowNKCR4TGgUwDeb7VauW20tBAHgFMwevXpdIrRaOTkQ5fp0qjw3KOjI7fpB8m8uq5xfX2Ny8tLt7xct/GibDEEoHGo63qP8KOij0YjnJyc4OjoyDkjyioNaJZlbj9BFglpuKPpxXfV3msjEEUR4q0A0wCwDlx3YwGwJ9CEhVrwsV6v8ezZCzx7DrRHNYbBEGEZwtQGkYkQtAHiNEY6SFHndWccAERhiCSOkQ2HaI1BYwyqpsEyzzHZbFDlOWxVIWhb2LoGqgrleg3b1hilI6SjFG3QomorVG2FKOuqCtno4YJggCyr9ziAk5MTV2SyXq/3hD7LMuR57tJrhM+qvPSm4/EYo9EI1loXi3KctJRVswI8xh+F8mzK5jNEU5ivXl6vba11CqcFUAxhGOqdnJw4NMFagSzLnNGjwdOKUS0EAvZDJO7vN5vNsFqtAMAZAYYYNFhEI5r6PDo6cvUBp6en+PDDD93iI11/wHFifQcA94Yh/i6KwhmBu37PgN/eSyPQRzpRwZWcUiYYgINqKvTD4RCz2WwbRqRY5zWebZ7BFAbYAEEdYJAOMEpHyOIMMEAURwgRIgrDrsy5bRFGkVs9GBiDJIqAwQA2SRC2LZIggGlb1HmO9WKOo+Mxpo+mGB2P0AYt5us55us5ojRCMkpgAwsbWZjUIByGeD4fYfz8ulvuvN0q7erqygkvySll7inw4/HYCT4zKIvFAnmeI45jnJ6eumKjxWKB1WrlYn4aDcJUKi3HnFkJzQbQYBB+M8dPwotGmAZGU4vsOyvu6HVpZOjRmaojiiPqoMGhASCq0es3TYPFYuE26+BzclxoUHWRGb/HZ2O9QxAEODo6wqNHj5wRINk8mUwc76IpSS30YnhGYnE2mzn+ivOn3Mq7aO+lEeDg04qHYYjWWtRbMkwJIWWcKXAA9gaVXmSQpYhiIDENqqJCXuYwlUFTNyjzEqENEZkIo2yEQTxAa1tU6zXKtkWcpojSFCBZFgRIkwSB7ZYSx0GACEAdRUgCgzAJcXR6hGycwcQGw2KI4XqIZJjg6PQIYdqtGzCpgUkNmrhCXr/E+fm5EwruiqQMOD0VN1RVeE4jSQid57l7LyPjWK2Y4xgr+85QqmkaV5PP8VRDQM84Ho/3vOd6vUaSJG5lp58b1znhppxkzOlFqZhRFCHLMmckSAayJmS5XLp3SyhRzP7QmJB7YMmvkojsN9EIX1ZzfHzswqvxeIzHjx9jOp3uhaNN07giI97TL/BaLBZ48eIFzs/P3ctwWOymKVvN6tx1e++MgPMW1qKSOnKgW79fisIDcGu4SRhy0mn5Vcg3mxxXM4tw2KGK0XgEU3XLhKuywnK9RJVXGCQDjLMxhukQgQ3QwqBuGtg8R2sMwiRBmKYwYYg0STCIY5imQVuWiKMIwWDQpQAN0LRNZ1ySCAMzQDbKMDmaIMoimMQACYDEIBsCn36audz0ZrPBxcVFZ7y24Q+LUqqqcvvb0ytuNhv3rEmSuDXzKuDKvJPoU1aeAkpDwPHkePP6HHfmzRnnMsSgYfaLYbSgSclL3aJLy38ZKhAJhWGIoiicAhIFcA0B0ZCmiNkfQn6F9lR0lvUWRYHhcIgPPvgAH3zwAYIgwGq1QlVVjuxj35k9oIFu29ZlbrjuoyxLt714Xzr3rrYPu629V0ZAi1GshANBEDho3jYNGtPt7MMUjX6XVt7PM1trUdY1Xp4XiKcVbG6RNAkG0QARIhRlgcVygdW822WonbRoqgZogMCEGIzHiLKs81plCWw2iNMUwXCINAgQkFmva8AAQRigtS2KsoCtbVcYZFrAAHVTw9Yd6WACAxMEqOuOCzg6OkIURQ62N03jmG8ukirLcu9tS4SaVEQSYdxoVRVKyTrlCGg8hsOhE3Aeo7GgktK4zmYzRzwCO1adiqM5cIZzXFCjYQkbwwcW+dCY02ANBgO3WIzXZDhEQ6kpOaDz8peXl84A8XxVatb7A3CkIuN8VhiWZYnFYuHGUjcRZRaB3A2frc/AKdL5sgzBe2MEaNHJ9Ldti9ZaxLJazBXR0IvUNYItyUX4y3JQEkOaRoqiqGPnY4t8tUG5LlGiRBZnaOoGVVOhbmsslgtURYcIQtvtLjQsS2SjUUcOAmiDACbPUeU52tEIsTFoigK2rhEmQUc2otvS3BmACGiXLSpbIRklCJIApjJAEmI2D1DXsRN2LoYin0FPB+zYdQoTYb1WSFLRCcvJjxBC0/tTMQnhiTxYgEUFpOfWjTTU+/uGQGN8zhvnluiD8Jz91XULCstJEB4fH7u3+fBeANxSXWOMQ0o0XNfX11gul4434fho6pnoQKsYNZPCZ6GRITJhmo/31DoEensqPp0SC9o4hix6+4XPDqgX4huFgV25aLwVEmxjYgM4j5NthXY8HqNtWzcpfP0zvSLQQVhrQownIeI2Qh3UCJqgW+cfxm5D0M1yg7IqUZUVTGMQmxibPEc4n8MGQbeJcBwjyTI0gwFsWSINAjRliboqEKURorTbUyBMQiACwqzbs/B6do1m1iAbZ4gGEaJhhOxogjwfoqrLPZjLN9LkeY75fO7WT/RV7jHeVgisws6sA+NpjUnpJYk4ALhqOH5OQ5umKSaTyV54wRdp0NDqCkBmc7QfSqYx3UYFzvPcoYZHjx7h7OzMKQgX9Wg+n8Qdt5wfj8cunVfXtVvRR6KSRKgaUD+EoOEkkccKTUL5xWLhXiDCFGfbtq44iWEO0QHlWBcxLZdLhzDe9R4R74URoIWmYNM7uNr0LQFoNUW1tcir5RJxkqAoCrfzMKFXGIaORKQAw0YoK4sgDBAlEUxtEJgAQRggaRKkRYq67PYdbOoGpjEdQVhVaLBEbS1qa2GDAFGSYJCmGCYJ0ihC2LaomwphGmIwGWA4GSJKo650uDRog7bbVyCwyOoMcRkjbVI0UYSmSVFVO+KMyhzHsUttLRYL57EBuBJdhgj0+AwNlCMgSXZ6eurGmHl5LijiPARBgNFo5EgvAC7rQpTG9Ct3zNUXa9AwRVHkyp1JfgHYMyz07sYYTKfTPQKPG8gQBdHL+vsCUCboaeM4diW+zEK0bevCK6Ibfk9JUSr6er3G9fU1Li4usFgsnHdncRS5FYX8msbleeQiADgDpwuKdNHTO9Ovd3blO2pUeFpfFlQwl6zFIulWmGk9V6sVqqZBk+e42noPVm0xlmUKit71+jrERychxlGIoAwQNN3mHiFC1FWNqqlgQoMgCnYvJW22gtJu887WojUGZVWhznMUYdgVCwGwpkWQBJ7N9EUAACAASURBVEjyBOk6RZh0G4gESQAbWoRJt+NQVVcolgUWxQLtfIM//skGURQ7T6regQrA8dJKPJJem80GQRA4qK/EKXfTzbLMFcNoNoVQHtitAdDwTBfaaE5et9piKo8LbWgoWNVJ40FjQC6B3pGGyV+lx70gmHdXuM7vk5xkKMFn0MIpjiWNIe+ra/upoDR+s9kM8/l8rySd1+Vc0FjrmDCdqZu/EDVpGKJVm4ro7rrdeyPANBBZaTZaWUK1QZZhenKCJI5dWTCrsuotoZQXBbItH6D5dFplAKiqGFezADYFwjpEggS16YyArS3CKOzeQ2BCNEED1AAadORe2cAACLcT1gCoqwqoqu17RrqXnQYIUNoSq3KF1nT7CSLsFguNT8Y4fXyKLMqQNznyZY4mKnF52SKOU+ftGO7Q29NDa0krc/Qa1zMjMJvN3LvwWMnGxTMcE3pyhhhUJo3PWZWpu+doLp/bc/MtTwCcoVFOgIrG/LvG1VRohebM8VP5dMGRpul47vX1tcuQMESh8Wf2iFyCos6iKFw9Bg0ex0ehuqIYrfUnqiD6pBEgoqNi81wSnpoh8TMod20I7rURoCWnIOuadfUYPLfYFr8kaYrBdn03AMdWF3mOzRY5EKYSphEJtG2Lq1mAbGphCoPa1EjCBLGJYVoDg+0OOFEA23SrDW3blfvCdIVCQRgCYejeRxoB3YajtkGN2m2k2NoWVVOhaArUqBHEAeJh3L2DYLt2IQxCXM4KLJdrJMk+46xEmZKdWonHbbOJpPgdcgB9hVUsGrq4uHCLkWiMKcC8RhiG7pVY5BlIumlsD8AVFjGtqEUwvC+w29+B/SXByJoGVS6GhEEQOFJNv7/ZbHB+fu7ScORU1AtrSo79UZKVJc9XV1fOQyvJRyXmGGjtA8lCogCtieAzKXLh//21GmpY9PddtHtrBMgW89VOnBRlaylIzMsul0vAGIRRhGS7gSOFnVabHr8oS4TBbuUWBzrPc7w4B46SFqY0qINuTX8TdOlA0xqENoRptmRb26CpG7Rli6ZsYEyILEkQZRmsMQishdmWDFdt2b1EPeo2EkHYrUto6xZt0wIBnDGBAeIkRpzEmJfWQXk+L3eyYbxNw+CXpmpMz+ekMBId0PNyAQ/jXTLTFFBVorIskWy5Fl1i++jRI6eE9LYXFxdYrVYuxicTzz5TcXQ3X5YZKwzW8mSX1t0aQyIcemn2k8aMxs/fuUdLrfk7DEO3eIf31NSpkoYcU96XcTwRy033ALBnJHg/Pps6PA1j7rpy8N4aAW6syVJMLfbggGnlICd9PpvttnfawjvdzrkoS+RFgaZtu5WAXgzdti3OL1p8ctYiKA0aNDCZcdDftN3rxvjaMbTbrbfaGlVddcc5iVEEC4sQAILO8ltYtKZFi20tfgiEQYiojTrSIACqpkJYb9fShwkae4QPP+xiYV3jzxoBMs00CBqj8/XYaZo6iO8LF5WRv7kBhm7WQeOpBTyE8vTu9M4svWU+fD6fu74ul0vH9jOW5qIujdHLssRoNNoLG5Tk43wTyVE2eD4/Jx/BGghNuenafpUDnzMAdtyUIg0quCtW244l/8/Qg4hTS5f9egIau75wgvOk5/3cIwEt/uBqQG5NNRqN3ATrBLH+m3wAIZvdVo9RmC229e8y0Jqv7QQIWOUWmQXKqvN6cRB3yt927xsMbeh+m9agbusO6jdAs25Q5BuYIEQchY78i9IIYRR290ODwARdvLAtCrKBxabaAHNg0A4Q1zE28yFeXmYYj3d789ErMFzyy2EJJzUHD+yW62pJsQowDSU9KF/SoucB2PNGVEpWz3FzU36f2QOF1+wLiTDm4BUGM+an0OtqUH0lF72+tdY5C16fho0IgIaIlYVqBGgAATilo5ISpvN5aaQ0fGH/aRzVc3N8ldPisxJFsc+6oEmNAMfdzxbchTG41QgYYz4F8DsAnqBbH/Nta+1vGWNOAfy3AL4G4IcA/ry19sp0T/pbAP4sgDWAv2Kt/Qev2yFjjMvdcjAp7OPx2FXMKRpgeFBVFV68eIGLiwtHGoZhp3T1FrYlFFqzK4v1q7bKssX1DHg07t4zaGsLG3QvHq3LTtFDdOsIAhu4/Qa6KiHsXi5qDcI4RFAFCMsQSZsgTELUqGFCg9B0yKCyFRrTwKILR/I2R4kSqRnjH/3IwAQzFEW1J1xD4TwoHFzaynicz+e/1JLxPFGCwm5VdioBx5lCTMGlYjCLQIXTOBrYTy1yXtTD6TE17lozz9V8nC9FQ5w/yoIiAh9Ca0ZJuQpl73lNGhg+K79DYpayyXoE1ilYa/eMI1GF1kBEUYTJZLJnVLisXRcwKTLwjchdoYHXQQI1gH/XWvsPjDETAH9gjPlfAPwVAP+rtfZvGWN+E8BvAvgbAP4lAN/c/vxpAH97+/u1WhzHmE6nbvEIK+OIAugR6P1YCJSmKTabDU5OTvCTn/wE5+fne+RSjv1BDIIAYRShaVuETYNwKyQ0Bi+vgNNJgCA0sK1FgwZ1W6NpG/cm4sY0MG0X09vGdjxBY2Fr615UGthu2/IQIcqi7F5kGm3Z/DBA1VbImxxV0y0lbkyDsA1RmhI//dEG18spptOdtyYcn81mbuEPgL0CExJ0jNvbdrfNmi40ojdm/M1rk08YDAavIC4tPPIhNBWBCgnsbx5CnkC9Jc9hVoAcAa+vjYqhnpD94tzlee7Sglrso/sQUM5YPq7xOYBXSnVZQ0Kj6iulpv70fRZaJ8H0JzMMfEM233E4m83cM2iYoESm7lTMpn34ou1WI2CtfQbg2fb/C2PMHwL4BMCvA/i17Wl/B8DvoTMCvw7gd2zXq//DGDM1xny0vc6NjXn86XTqBI41ArSguoKNsRzQCQKXCE+nUzx//hyXl5duIpREDMMQZltZyKapGmstLq4syk+AYRx3Cl9twwV0zH1jGzRtRxbaxjrlb6utQWAmwRr3/oI0TJHESff+wrgrDqqaCkVdIK/yzgAkIYwJ8MfPKvzw8xZZ1kFNvxyXz0E2XhVdawAYqytBRc9MpeE6APWa6s18b6SQlZCWXl7TubwnlZEeXWNbJXX5PUUy5C60jkBDGPZJ+0lijorLuJwKr0y8hgF0OlxzQvJZU8oMVfV+PoTnXCwWi15SkIu7yHnoQiOtWtTFXZwXXs9vb4MM3ogTMMZ8DcA/C+D/BPBEFPun6MIFoDMQP5avfbY9tmcEjDHfAvAtPZYkiTMAGvvwAauqcqWUTInFcYz1eo3hcOiYZ0K+4XCIly9fAuiq54ptTt0Y0639txa2bWG3wtrKJK43FrOlQXbawrYd8dfaboEPgu3OOHWJtmo7RbfbeDzsXiZCI4AQaIIGjW3cm4uzpFs+bAOLtmnRmAaItrA0jvDZc4MffmZhbYumWTmyz1VIGrMHMxlTA7tiIcJVfhfY7Wqraw+ovKxy85lnjUeVSKTQ9xGM+vovxuqM5dkHJcIAOE9N2M11+b7C0Uur0VYug9flfZS7YD9p9IDdWgamL7XwSlcs+v1WQpbn0ej5qzH5A8At2KJhadvWbWfGknYSmX6h0iED8LbttY2AMWYM4H8E8G9ba+cKra211hjzRmbIWvttAN/eXtsqVNKJJjnEiaYF5wtFwzB0m21y4HWPOioMB51eU1MyXr+2E2ZwfmVxdlyjKiq0deu8ehAGnWGwNSy6QpU4jB0qcOehI/5sYN1PEzRowxY2tAjiDiFE6BYTNTD4wecBnr8EwnCHgqho3CtRFz2ph7fblBkVWjf2VC9FISWjzhhfSTaeyxCByIBGQwUb2F/hqShF02pZlr2CAvxQg8aMCq07Dfs5eDZVPp5HSK7G0ZjdylIiAzV6jNXJo7CYCNgZEWDHjyhPQU/Nn0P9ZIhGpFDXtTMCzGCoQblLAvBQey0jYIyJ0RmA/8Za+z9tDz8nzDfGfATgxfb45wA+la9/ZXvstnvsFXko9CG8okBoDtnabott7oxjrXVbQ83nc0eEGWM6UtCzqJo5ALY7A20F5+IKuDy1GGVdWg+2K/AJTdix+uG233FnGEy0U/4oiBCFUYcMos7rW2O7xUNZhCAJuhLhKMYoG2Gxsfgnf2RxNWsRRdal+MiIc9UcS3OpwBwfCpwWwXDPexZD8TMqio4psGPFFXpqeStjd+a/FZnooiCGXQw5dO0Hx5zGQMM08hRaCKWbndDbK3HoG8S67jYg4VZdwP77FzkuLHDicVYasiqSNQ50NGrc+H8aWmBHACpHokZXDSrXLTArwfUDPtfho4i7rg9ge53sgAHw2wD+0Fr7n8pHfw/AXwbwt7a//64c/+vGmO+gIwRnr8MHEJbNZrM9goaDqPvVa7yn5az8ju5Gwxc+MH4lquDgErLWdQ2zTR1SoZo2wPf+yOLTj0KcHrUwpqsObGyDINzW+7ddKXAbdFAfZru4J4oRRzHCuNswJEojxGmMOOt+wiSENRZV2+Dz5w1+/KKFCRtMJt0zE66TwCIxSrTkUqB2tz5e2Wv+phJTgbiQh2iLqEBJJ58d57ixhFcNEP9W9lw9NtGMGgh+rrv3qJFiY3GX5uIVajO9SIeg71XU9fpslCUtoGJjKlrDAe0HZZGZBUVIzAowQ0JDRUTB+2o9hh+mKWegoYoe5zPcNSp4HSTwZwD8JQD/jzHmH26P/QfolP+/M8b8NQA/AvDnt5/9Lrr04PfRpQj/6ut0hArOQaJ1VyvOgdDFFswOxHGMsixxfX3toBqFW2GlDiaNCavhONEOggGoqgbf/6HBdBLg6ScthqnZ0gKBKx3uHmD7IvWge7dglHQlv0EUIMxCJIME6TBFOkiRDtNu5+I2wuXzFEXb4uyscApKYWNT4o2wnBtqKivNxrHiuHB86a20wpAVdS9evHC5dBbZ+KES4azGxjqeHGuGJAD23hnAvimhF0WRIwY1hqZBUWisRT0+56GKqjl7GjHNIPhoUxWN5KGSmZpRocyoIyGC4PWJgGhwGPYoulXZ1pJ4jhHnVsdKyVYNAd+2vU524PcBmAMf//M951sA/+YX6UzfA1FY6f2UGVayRGM+CjoFWQkfDrpCUQqYQmNDAdha8MW6wf/3Txp89AT46LFBOgi6kt+mdTyAQfe+AhtYmMQgjEKEcYh0mCIZJAjiADayqAA8ew48e9EiCIHj4ylOTgKXX9dtvJUt5jiwDJphUpIkOD09ddtqsSrQ50NY+MNyau5ARJac8TKFnve/CaKyD1ylqN5eawy0NoAekMrJe7N/ulORIhIqga76ZD8186N9pdKqAdFnpdJroZHySWoIed5oNHL94NjQAGrzCT2GSFp85Muv8gr8nM+usv822QC/3ZuKQWV7fTLFZ2Yp2ApDAexZXd+K6sIMY4wjD5fLJeaLBUwQIM0yVFvl4r0oKPQwqzzEH33e4NFJi7OTBmlaAU3rXltmrEEbtmiDFibtXl8WD+Pu/YIweH5l8NNzi01ebb1Yl76cTqeYTCYYDofuJRTMgvB5KBh5nr9S7kzGu6oqXF1d7VUFcsmvkqM0GFoirGOr241rOlARGpVJ54YEGr2qhhS8Nz2sIjQ/lFDPrjIAwEFw7QvPU9lh+lRfPgvAZSEYRuqmISqLdA7K/rN/Cv35/LyOK1Hfyg4dD++pfffHUp+d8+kbEn7nrgzBvTECwP4KKU4mhQfY7SSkVYI0AErS+IwqB5kTzSWu3EtuOBq5wS+2b5RRxa/qGoExGAyHyLZe+GqxxPOLHHFkcXpsMRk1GKQtom02oAmazhAkBiaJcLWM8NlPgdXaAKbZUzDdnkoLUugZCa+JEDRXTk+qG3dcXl5iPp8D2H8Rhr8Kk2XWl5eXrsRXDagqFxURwJ6hVYjrZwvYlDnnnOhzKMehRBq5BCUg9Zq8rqI+JSqpdMqdUHG0SlFhOMMEJfgUfis3pUrue3HlRfhsfC8GDQXnmNwH+60ZHG36fKoz+mx9+nRbu1dGANgvAFFvD2BPIJlqoTBrJkHjeg0DtOqLsNlai0GWYbxdk1BVFcbj8R6RU9V1V1m4RRDWWmRZ5hbI/PS8wU9eNIjCGsOswfQIOJla2LDBi2cVFqsaVbNdJIAG1u4IItaxM4xRGKqkHdfXazhDmEi0EEURlsul22WInpaxv880M0PAF2ZyDJU807ShekSOtQqhpiz94/qbws755b6FWkbMylHdspzyocqqC4TYTxo5GhleU5WVCqjX1VSjok81AlRYRSl8NkWyinLYD92dWfP/5Hl0P0jucqRhkD67ko3+td603TsjAOAVAdKYEthVrTEuJAQljNJQQK06v0sLy8FlDjvLMsRbNnvPcxmDRkpeiRA4cZpqWm5qLNYWPz0PkSQGra0RRctXatrVq8/nc1fZpmkyrSdnrK7pMHruMAyxWCz2tv9W4WT+meOg6TaNPSmcShzqs6l39BWIv/2SX8JXRS9AZ5y5dkGXNHN8dBm5XkMhcNu2e2/9pQL68bUqK4/TaPjelRwHx9ZHMESVmnVQI0eH5XMgHLvFYrGntIqCdK3L3iI4u58yZz80o+IXFr2JMbg3RkChjJJPHEjdFNO3hvxMiShgl4/WGI6xFoC961VV1W13nSRo2hbr7T58QRB0rxnbLpctt7FeKSvgGP+xmImtrBpU1cYZHp+g4kRy8riDjYZDPjmmSElJUC6n1Vie31e4e8hz8DiNj3o638MxtFIeR40uDZXCfRoOKoXuSKS5dxpWhnpKZmo614fBKvQ+KgyC3ZuAudEn08fcXYljEoah2yhVC4ZoeFVmeG91CDr+vsfXzISOhRoAGjpuBKMOT0MoFioxu0J58I3W67R7YQQ4kBr76d88R9l7LZxQKEeSiedw0GnVlVdQS9223U7E/L+y9GG4e0tPHMcYjkawzW6pKrcyn8/ne0rjx6r+3oaqZIwJqfTAbiceAHvQD9hVrSlRpOvlqYzq6Xxl5nkkvPg8PtTtizvVM/qGQpUF2EFlPpNWQmrcrRV5DIWqqtp7kSdXJ2qM3sdJMBbX+7HOguOyXC5xcXGB+XzulF15Gd3IVStZVWY0+6LPo+gT2M/vK0nK/mn1JoC9reDVkBApKpnL6+tY+vN0U7sXRgDYeX+1jvqAaj2BnWApXNLBpQXV83yIyGtRGRjrOWuKrbGx1r2yKwxDjCcTjLbFPBxw7vmnu9DQMivjy3hXlZKKrROuXpH99CdUlVth/k1CoMfVMJLIUsHV79AgK6vtw1P/fj5K8M9TxdC5ITJT0pecDl/lTaHXPvu7+RABKNpZrVavhAua1dBnI0rRvRk1HOA40+D1lSGz6RxqCMs1FmpI/FDKD7e4S5PuSsQ+acaBRvk2Q3BvjAAnUFeP+WgA2CejfPSgqR5Nd2n+2rfmhLd6TWArwADCKELbNKi3npJhR7FdssrST94fwF6cpta5LxRh85VFlcFHRwq11euoUukxNjUahP3KaKvy6Pvw1NsxJavcgfIKfj95X0VwGqqosaccsP8cAy6T5nd8o0oj7zsPlgK3bevqGPQ7HF+F8zQAvKY+O7kiJWl1jtQLq8Pym/JclE+VfV09SfTL+85ms726CZ1X/fHDFv//e7rXe/RLblQgHQAVdi0UUnaX39VzfCOgk0iLSSGn16ACsF6fe/MxLszzHI2EFYwV/by3WngSeQrllDTz+0aFVmGit6GSqfLrG4d8j6zEWR8SYIypsF/HQa9PWE1vyP76aTBl1TUE8QWe4YJmQ5RfALCXLlReRwVf1zTwuXg/zi0hNdOlup26PnMYho6f4BhqiMF55nHKl/ITPLfv+z7fRXnVMWV/+3Sgrrv1DtfX15jNZq6yk2OrlZaUKY6VoqBD7d4YARUWtejMr+qbc3Xy/P0H1ZPw+4ouFCYpE0vB5YpEKu18Psd8Pu88U9ui3Sok431VaL02m09YKfQHsBcTKifgIwjlAvw1Ahqb9sXoOh70sP6CFfUe7CthspJe+kpufo/91hdtEjpznNk/n4lnHzQzwL7pmPUZHB3PPqNPXoHpNsoKGXxmQIwxe1WP5G80I0UCti9jonPsk6X+uPahgD45Uc5ouVw63qJpdsut63q3+IjjrJyMhiY3kYX3wggArw4OHyiOY1fYwx2F+KAkzjixShz2FeEomcZrV1XlVpTVde1eKskKu/F43EHiMEScpqhkbzoaCj/9pmSVNh+yq4D7KTQVJgC9Ss2//WNqNPqUW4WD52iooMroG101rArB1RAxzvUNmio7sBNM5RzatnWGhAbL/7nJeAG7ylEdAwCunkCVheEOFYpjwI0/WL9AVKgFVdqXvhDIRwDAPqFL2aFzUgemxk4XKmn2wc/EKFrxr3NIJoF7aASorEqccHsx7slGS8g8MweHMRi9u+bXOekUGi2npQA0TeN28OHbcdkGWYY4irAOAgcvWY6qAndIYFWgtSk09fkPvZ4f+/N8jT31s0PGA9hfMux7LFVGGhQqPp+B4QCwE3ZdWMMiKEVHGuP3eT/KAO/tpzF1fBVhUKn8Maay815UAN9D+mPdtq0rIlssFs4IALuqVDVCipK0/31jq42ZDyIUGgAaUT+zw1Qg+8DvG2P2dnLyQxMArt7kULs3RkC9Cj0NlZRIYDQauWWbTPkw9+sv8SRc13Jb/6eua8Rx7F5Yydwrd3XxFYWWmQt9fNhHjwjslkGzqVJqUzKJv33F0T4Ar6aD9Fp9kM+Hq+p51UMrD6CFKBTw8XiM4+NjV4VIXoHxLLcOJ3QGsGfYaFT03qqc/rkawugxGkBFIbwOx4WKQwVWEs2H8ewXv6+ZEhq9PuSlyk1kynhci8o04+CTmdrHIAjcBrJElIrS/FoO5aF0nPxx7HMu2u6FEdAJ82M7FnnwffGs7OPaAebeaQwUlhPCKftPwe7zNJwEFgBREDSFprFoWZaom8bxBMAuDPGhqD6rCqDP8mpTI+RDPFUIHmfzvTnwKnmozQ/D/DQXBU0NM19qSujMV39ToKMocsy7prl0QZIimz7F6hsTbeyXlgyrIuj3Cb8Vymscrf3heYTqurqQvBRlQueEhukQ2lG+QslPzhOdENN9ihYouzRKutScBKvKg4Z35EAOtXthBLT51lkZa82n+kIOYG8SgE7ByBArk0+hZOppvV67Pd50ww32g31x5BS61CG2k1JulV7huFpmPz70n9f31PqZejZ/jPzx4hio0vljpOGFknY0bDyX3p3eFug26lBOxo/hGbpRWZbL5d6zq9Jqma/20/dcN40NveEhVMR5ZDrTJ/U0m8PvaMjGZ+N4xHHs1jLw/Qnq0WkoldX3ZRjYT0/rc5Vlidls5gyWb6w4hoq4FKEwpFAjy2e690gAeHXnFP5wwwmSTazVZyzGAdIiHAoRFR+Ae0uOcgpMvRDec0sqwlyShroJ5HK5RLj1cFEYoo0iwIPtbdvuIYQ+Qe5TZG2+x/chPCdW02t+OHHbOCuk5jHGmMfHx5hOp7DWYrlcuq2z+UISCpwxXaHUfD7f2wqeikFEpgSYQmJ9XoX0atD7PDewC7m0XFo9Ia+rRkDDD4XYvvzpONPjU874PTWivJ4xxr0anmjRX23oh5A6t5oSZTig9QY0XuSjFFno6/m4aIyI7b0wAtrUG3AC5vM5jDGOsGO6SuMvQlMqhkJCjc04sAwlxuMxptMpzs7OXtmkk7wCX6e1WCxweXnpXtbpk0xMO/FHF+r4acRDHt337vp/FU5gH/3wuHIgPoGmSMGvzeCGGZPJxO3crONAAtVa6zYjUVSm7wlU0oocDUuafaZaEY+iOHpy5QF07Hhf8hZxHL8SWvBzRUZ6LTUqfTKoJCX77Bf4+OsojNntV8FdmogoeC+fD/BDN8q31obQyFBu+yoNeU/OE8dADYnf7p0RUPioxoDCw4khNOfCHBJ63KbajzHVUobh/tuOgW5iSTzuFhq1aNsa63XlFums12vMZjNcXl7i+voaeZ47haLXoqfbbDYdilitsN6udtOXgPSlvA55cD/epcL7i2n8EESJQMag9Fb80fQs91jgy0uYh+Y5hKxlWeLs7Mx5fzWwNKK6oy/Ld/3tvn3kp8/B51Tv3hcicRzVKPlzoddQBOQTlHqOKqBvSP1CH56j0J5c1Xg8foW7UePMviqRCOxzNYqENSTmvdTp8F40JFyXcqjdGyOgk8u/gf3XjGl1nhJ0JACXy6XLGGhhCmO/NE3dqkN+j9fUGgNO7slJjQ8+iPCDH0Q4P4/20opUFpazxvQG2+ehN+Srvxbbdf7XV1fuhZ2E2H7a6abmE2cax6s3oGHykQDPHQwGODk5cQKqW5dpTOov2AF2KxuDIHCbZPA4v0cYzPjfD1MIfX2Y7MN57bP/mZ9lYIjB56dS+PD7UGP4qAuPNOzR1DLRKBGln90iyay1LbyH9sdXTj4T70VnRflU3oKFUIo+NQ2rBWg3yda9MQJ+bhXAKwPBCQH2F8CoIFC5tbItCAKHGuq6dgaFsErZVgqBMcB0CgwGBv/0L4f4fmTw8uVughVCqwU3JoAxOyg6nU7dZF1eXmI0HLotva6urnB5eemE+6aqrkNjplyA7/X7jlH4CJ/Jmfhsuv6t8JfX0NifbDm9Ln/rDsa+B/fRgP6fQqzGTpGCQn4NR3hffk95mj5Z0+8HQeBqUbi/gRah8dkVTTKc0LFgClvDTF25qP3se25tvLcaORYsaYrWlxt1pHyTkRpxv90bI6DkiH+cyq1lnPodCqjvGTjwwL6X4uacnFDdPZYbewDATz4DVosAq3WA1apTInoBGpPRaLT3znuLbv8gRStAJ2x8gSghuM9a+80nFJUP8AWGSq6C6xsC9UKMnxk7+jGwrhvQdJcKq3pVogmfh9Br8hlV8ZUn8T9TRt1PJfK7en/2TYuEKD88h9dXpdAFQicnJzg7O3MhEREkQ0f16mrQOP48l8bg6OjIEYW7MNO8kk3yx4Cyod/TFa76fcqD1hCQsy73lQAAIABJREFUg+F+le8FEiAE89NDfEhWoXES+n40Deh/nxPm1wdw8Ppiw5cvd7ldLVFmnMaNLsiaE2kAu2Wr5AAI+7XaS/vF/vZ5LWC3HbY+qwog+8Scvb7umwy6lqUq0aR1ADReNARkof10FEk/XpfEJ42hxqx91ZPAzojos/RxJX3jo97fDzXYFArrZ4oy/PHT1Xy6XmI0Gu3taalolUZHj/FZSCZr/6ng9NB98kil1+PKu1A2FHWRh1EyW0OEg7p38JMvuannYCO0p5BRMNn6hEMFXz0nz9e0Fb/L//uD5RsWvhLNJ400RqP1VSusEI6E4WKxcO+d8ydKn8dn0dXA+aywQmSNU6mww+FwDy2wkeiKomgvjmcqypjdexw4rlQOEn5UJIWoHNO+LIVyG/w/FYKwl1mEPuVm088VLfnckj6rLzvALqvD3XqstQ7Wk11Xws43JERZatxVoRXJqHFSb+7/6LP52S1emwaAssf/6y7ZN4UCwD0yAprjVVaYFtG3lsDh3W14DfX8PKZxGfDqDq7qeSiweg2FXsC+R6IQsQBpo95/q1isPeDrwXSf/0M/bD5L7v9oVgJ4tTaCHo27D9O4KdOt9RH0RLqkmoiMEJdKqwJKRKEGnfdRJEV0RcPOeg1Nb/kVhr4i6E+fEVAegoZKx1Djcu4QxR2aWLKui4aUT/JTg3QEJE21XkCNPLMGDA8pM1zN2sed6DPrPRUNaIGR//w3tXtjBJTkA/aVURXcJ8FUMfpSReo1/HjQNwC8jhqQMNwvo1XLzQFXUsyPxXiMwqHMuXrNvrjQNwJq4HwhIDJgU4+ir+jWdxvyOJXT38VIBZsFQ1pBR36F9+P4+eQi51Kr6ViRSCPA+zGFyHN0zlVBdC54L99L6pjRW2vGBMDe+PN5eA1/bqqqcvsOtG37SgWqrjJkaKTEnqIhZmfCMMRms0EURTg/P3cFQn5IS9nhuPhooU/RfQN5qN0rI9BnBf24kh6cA6UPqh7ZWrtn9f3B8nPEfcLCpsZG78X+0Arzh7BfPShRAg1C36unb0MCHCeOj68UAFwmRHmDIAjc67fJX/D7hPOKfvzl3OPxGMPhEOfn57i6unKG4BCZSZhKo66ZBY2d1chrVsBP4+n4+HGyzpnOU598kbdQXonoUJ0PZY1pUxov9oPPTWVXOdJKVs1IMaTgtdbr9R7JTCPJZ/c5EiWP9X4aevkOT5HOTe3eGIG+pvE3J5iC5X/GRovNyVKLqgPDSVHikJPKOF/Dh750E6GwKn2ft/cJG/6t24/5yt4X9vD/ykOogaPQ8HPCdF2Gqp6ubVsnhHqu7orMUEK39GK4wT76xkwVn3lyRRwUdt3ohWOm6zZ4TZ/76Ytz1bhzbihD/OG1qYx6LR9dUDGpyBraADs0pulBkqhEAUQWymcRGfAYQwZ/ZSGvxY1tuK26llv7qMcPk3Q+bmr3yggc8n4K0VUx+phVPxbyv8fP9EfLSgH0GgH94f1poRUF0DLT4x8yELq9l7UWrbWwQhbxHofGyecH2G9NyTF+5+YgURTtpQQB7PWJhB9f8qmemTyBoh0N32hUSTgyXOAPj/nZG1UWwml/XYEuWjrEdHM++gynoj4+kz6/ZmloLCg3NI4ajyuiIdfhV/6pI1Ano6Fo27Z7G5n4IYPuMcB5VZnxeRHfSflk7KF2r4wA0F9D7x/3408/l+zHUzyXTfkEZWn98/3rKCLg/XwDoCmbQ0bAzxG7ftwQ3/lj5LPbfh/VI+m6dD925uf00CTFfHjMaysi0AUujHPp6ay1e6w1lcGH1EQS/nX1WB+s9Q27js2h8/mbxlEVW+VCU7F+ylrvoySxX5Gpz+ErpkJ8NTJqUP0xUAJawzDe3yfP9XneGySgHe7z7Dqx6qV1olSh9Fr+PfriR1/BtWkffCVWb+cThOrxtdBDDY5jjj2IexuMU9jdFxb13UP7p+fSEyuhqvehYeVnXLGnWQ0ArlybyOH6+toJtLX2lc1X1SCoAeurg9dn0vn059b/jHPWp2iq/HoNX3n6FMsvhvIL2TjePjpVOVPl7quP0XBT5U4RmKYJtRDJH7ub2r00Aoesl48GFK76fMGhe/gcg07MTTE6sF8FqIrFyVGo7FtyfxL70MBtCODQmDH+7suKqECx/wwP6IXoyQjp++aERodVllmW7cF3Pg9TjZwjrZvwx9d/fn9MDpGmN8mOHtPn97+n8P/QNQ/dB9htkc/va6FbHzxXQ8D5Z0jhGyMeU0Tph6y+kdcFW35IeZts3QsjoN5cPZtaR2WNfW7Ah2l+vOx7Ng0HCEf9WLQvFNEJ9L2rzw/4td1Uvr7UzuuEAIeaptx0gwwfUfnelkJY1/Urq9I4D5ouVLacrHaWZSiKAldXV8jzHPP53Hld7jFAUksZcK0D0TE8JKy+J+6bH53Pm87zr++jgD5HwvHQOdfUqBJ/PoGofVDjQMOrCEXl3Z8rRbfq9PrG0L/3IR6F7V4YAeDViijg1SIgrdJSS+grlKIEtr6wgv9XRfat+CGhVMX2Pb/PEyhR5FeU3TQ5r+uhqLD84Xf74KwvhL6noEHhdm1AJ+iazaAxUOG1dscBaBqUL+lgibXuBalLq2m0dG76lF/P08/9ONkfr9uMbJ+Cab0IjaUaOV9OaYQ1NPD5Kj+MUkSh8q/3952hhlGUP6I4nf/XRZf3xgio9dXBVWWjgPqDT6KHjQOlhRxsfahBBc33+n4sqP1Uz6A8gMbefdwBj7EPXxQFaOOzKMRUpVKF53iptydPoOfrG5ao5CT5FErzc//ZgiBwiGE6nTrDwlWHq9XK7djE9zjS4/UpsrY+GN/39+uMrX8t37koamLf+T39USXWY+qtqfh6H463zpP/HGo8lCvQ9SqqA+oEb+KWgDcwAsaYEMD/BeBza+2fM8Z8HcB3AJwB+AMAf8laWxpjUgC/A+BPArgA8BestT+87fqHlE2FWSvj/PhL2WYNA/wB8EMDbVp85J/nC5SPRPqIOIVyh4jBN23aN58H4Tj0CSSAvRhWv884nm9VStPUbevGHXLyPHdbr/XF0uqZOT9MnWVZhqOjo71dnzhfPrLoG5dDRrzv70NjxnYT1wTsrx+hkfRDJ00fas2Boi3+9r2/byB8h8ZzdYcrIkg/tFTy9DYDeJMheBMk8G8B+EMAR9u//xMA/5m19jvGmP8SwF8D8Le3v6+stf+UMeY3tuf9hdsu7nMCWmHme38OqG8MDkFJHQgfbfgwU7/HOBDYpQP9CebEanWeX6DUBwO/KBnIxvvSwAC7rIlCUv2hAis0VaKQP4SZm83GlRZbuysK0mfzDbWOie6Io6hDayUIZf1YuO95/TntG7u3RVV6HzWySu76Mblv+IF92M5zVLa1OpDjzf+Tc6CX19BSjcGhceJvRbM3jctrGQFjzFcA/MsA/mMA/47pZuyfA/AXt6f8HQD/IToj8Ovb/wPA/wDgvzDGGHtDL6hEWiShhSVqEPQB+V0OsB5j6yOLeA0e861kn7CpN1f0oXyC33QibiIC31Rw+77LWFXRDA2kCi0NmSqvPxbKY/jhlhpGv08cD86Hf32OQVmWewuoaAh8XkifRY3uTePxOmN3yCvqZxoGEKLzmCq1PjflU4uJ/PHV35RXNSDM2uhmt36tiTpB/b4aU1/2bmqviwT+cwD/PoDJ9u8zANfWWtZ4fgbgk+3/PwHw421HamPMbHv+uV7QGPMtAN8CsKf0hzZRPATj1DP5AqQKrkLU5/H98MH32D7cJzJQxt+30r6H8IX5Ngt9W1Pl2o7p3t86Jj5c7fvRcQKwp/icBxJQfuMzEUmod1OlocLoSzU570QbfWsq+p77bcdN2yECUedLZYHfoRz4zL6S0r7BJbrwDQTHw880+SQzz9d59bmUQw6nr91qBIwxfw7AC2vtHxhjfu2281+3WWu/DeDbAJBlmdXtrri0la9j6iOBfBjvk219mYZDA6MWVI/xt6+46lW5akzh4k3pGv/vtxXovmfjMZ/IBHbsv0JS/T8Nro/IdI87HQdgvyy3qrp9FblGgouoWK6s46ipTW5s6vMZ/vPpmKoMKKn5JuPG7x9Ci2rM1YjpBix989zH7Cui9BEJjQCRmG8IOXfAq9vy+zIKYM/p3CZnr4ME/gyAf8UY82cBZOg4gd8CMDXGRFs08BUAn2/P/xzApwA+M8ZEAI7REYQHmzG7Pe/6BJIDxt86sH0Qi4PXV0kH9KeffCjYN7CqUOrt+wqCaFj8H+3DXbbbrqf3p2fn+Gj1m35G5dSNLoH9egmdOwB7rLXyFUQFvgejEmn6VD2uKqF6PDYfJapC3jQmvmL0GRxeT3+0pJhNl/byeTlWGs76aNM3Yry/r/w0yhw3zTodIpv7yMdD7VYjYK39mwD+5vbCvwbg37PW/hvGmP8ewL+KLkPwlwH83e1X/t727/99+/n/Zm+RUBUkFcY+uHvICLBpWsS3wt5zveI1/c/6jIX2mRPsw30/teiHJnqfu2qHwqW+YyrUGu/qs9Iw+BuSAvu7N/lZCCUm+xb+6P2U7OorsfaFXElH9tEX8jchW/sQJsfID484r33XUGfFvmsfeT3/fr4c+4iWx1UfaIT8fvJcX844hzcZgrepE/gbAL5jjPmPAPzfAH57e/y3AfzXxpjvA7gE8Bu3XYgDqcUOPsTqe4g+72qM2WPG1TreBsf74qw+JKBVebyOej29/k1/v8vWFx7wN0MZH1aqwPiFRIS4bKr8Kpw0LNw0hIoOvFrqWtf13mpLraXweRW/r7yXkpZ9XMshZ8HWZ5x1DH0ewJcXLvtlf3xZ0bDSJww13chz+8JPXx777qNo1jeS3N/gUHsjI2Ct/T0Av7f9/w8A/Kmec3IA/9qbXNdvOuC3wei+2Eo/00FTa6xK4YcF/vcIQTVDoQqg1V2H+tDnbb+spvdTg+VDXfVawH5opa/f5nV8peR3gFffCwmg95461j6s9edOm39e33zyb79gjM1XDN+o+xBdjWVfmKdoSPuhaWaSq+yzXzjko54+WdT++vrRF2K8N0uJ/QcEDkMZ3xrr3/4g+UKn5/nWvY8T0M8p7MqOK/TT+/ok2rtGBbd5wD7DRzivQq9em9VxdV07XqBvnYH+vy90023F+opbDhn5Q2PkG59D17rpOrchBH5Pn0mfS8M8ohpFUP58qAFgBoVKr6sRlTS8yWH4RkjRwJs8I3CPjACtpcIawnqNR33P0ycI/uD7EMv3Hmy+wvhGwK/O81M4fcLyZTcdmz7j6RsANhU6n9zkeVpdqIZAYS4VgR5Oi2Y0rw70w3ft56G/ecx/5pti/D6jeCjE1M91vPi5VoGyPoDn+VWZ/A7HQZGk1lTwcx1z7TONC79zyAj4z3aIHNd2b4yAr0DAvtCqN+mD8Dyf1/KtsX7m51v9+/r39uEqsKvyYgqMBS/+Ob6xuWsE8CbNh7nAPvtNQVSF0iIWPp8Knb902RjjUrt9a+A5/rz+bXDe77/+9v9/qKlj6ZObmwy27wzo9Wn4WG1pjHGOwFdgHU/fAPeRjr5MqiFWI6HzqYbaf96bxhS4R0aAzbdoLJywdvfWnNsmrS9+8s/pGxgdTL0/hVhTM8poq7JrVV4fyfMu2yEP2udF+wycKqYiLn0+hfi6qaZv7DRzQo/pG5bbiNSbntH3tF90bG9CBr7h8Mesj7fwjSzHos9b65j6n/togN/h9XQubnKKN+kB270wAvrAhyCO74UA9MIcf1J84VAE4CMEvaZ+rot/1CgcEgJ+7vfBt/B3aRR8j/U6BkD7pL+VK1GYyudiSDAcDjEcDp0XZCZAhdUv9Q7D0L3Qg2sI/ExDHx/T1/e+MehzDrchC713nyHo+/9NpKW2PkTQp/w6Vvr3IcR0k67oWL1OSHovjIAOiJ9T1wIWH970Wbi+475S6LUp2Fp77a9T8K2/8heHQgi/H18GEvD7oMSf/9lN39O50HhfF8doakznRpGQGlFdXq3kl+8d/b6+7ViwHQoF+rzoTYrjI6U+VOL/nzLcFyZooZbKtxZj9fXT/6Esax99svdQuxdGwBizV5bqf6aDeFsB0E2tb8IUUvEcHy3ocd/AqHXvQyCHFFDRxl22m5TKHwt9LjVsWrFJr6/jrjvr6PJaa3dvK/JDJC0GoiHQUOqmjEFfv/uO3TSefWhMn1+9sBoC39D7ynfISysBqIrOppWEJBMVYWqFZZ+n12vxObSIS9Ox781biQeDgUudaAzpW0t/MG+CtvzcJ+xUUBR5+OeoRdYqQN7Dh2yHvMQhw/AuWh8M5P38jIAe1/Hgca3e7Itn/Z10OV7+3gn+Jiv8WwuEfCXqe6bXefab2qFQgT+ULz1fjV/fOKh8cV8BlVPKb989+8JglTv2oe8a/IxZAyV1fQRGTu1QuzdGoG3bvTfDsGkZqoYFQL9w9AkQrSr/9puiAb0mBdZfwaXf4/18nkDv18eAH+rLF203QVif/+g7rgrYJ3Dsbx8a02fXMaAx6Bs/f1w0PPDv2ff/u246J35o6iNRlUHNdqgnVmel2SLehwuQtJy6z0ndFJ7wOA2Bn2b3OatD7V4YAWutexe7WjadgL46caCfeNG/VbjppQ7Bdp/g0zRgX7qP3tBfQKTX7puIdxECvM13fOXrC21uEkQqhXIQmvLqI05vmoMvox0yiPq5Prc/73xeypV+Vte1e2Ozj7wo0wyR6ODUAKgh5v/7UIgaor75YWjnI0C/3QsjAMBZU92xtc8z+Gk3Pa+PNwCwN6A+BPYFkZ/dxPzzezQSfaWebL6Qv0tv5jc/JOAzKHS8aUekPi98SFHU+Oq1eJ5CVR1HH9V9WWGT/1yHlJ3HlCugAegbJ2ZP+PxEt76sUn44FloH4zsynxjve4ZD6C0Igne6gOhOmw9n1LuwqeVTr6EDzIHU7bcV1veRfnptJXWoML4xYl+1GIZ99o2L//932Q7dp88L+5D3ddCEj5J47JBi3JQdOdRPPfddjeFNY+R/pmPFdkgZeR16eq4p8fkBn2i9SRYPzY06MyUBNbTV8OzehwMqjGp19UHVgh6C1ip4utuLxqdqSA7F+CR4eB77Qg/qC4ySaT5S+bI9/6Fwic2H+Id++p7B5xD4+SFB5bho4ZAaer/fvqG96+Z7/b7P+85RxdLz+kJQfu6Trbokuy//71/3dZ5DSda+UFb3J7z3RgDYXxvue6ebBsU/R9NSfZ5FjcL/397VxtpyleVn7Xs+bm8LvQWTpraN1NBACAmCjZZgDKEYgRj7BxE0WrCmfxCQmCjEH2jiD0mItUbT2EAIEGKRSqSpBtSC/7RKgQBSKuXD3jYtlFraW3vP1z3LH3uefZ797HfNzDmXe/aannmSnb33zJo1a9551/N+rDVr1CvgRx9n1mMi6+Tt0Lb7ec8nGZQ6tCe01N2MZBx1RFfMKC71jqNEAszfE1rHKGxzeZ0v2bV5IRo/R230Y9Qr4jFe/2QymS3O4nMqeLx7BZFc/Nyeh9KyUShRQjUkoI0tWYnShUTb3ZvQbycK90Q0fvVzuJulLF7KIRyWR+A3XhduPWbvytPr4bfKTDP8Top6Lbx+zeMQahFpDZ2I2zr6+SCCPvUoqTmhezmf8x+FRFqf7tdlxCIyLnVsYH40yuVEvaYHNoicQNTp+dutRiTcqD53ayNSUCXVKcma1HK3St0vn1fgU4sPwwsoXbta+pnsUsIugAmwoKhqgfifBOBPT0bXxDJOplqOSqlZ9WiyUETehwH3/LwDR+VVJlHoxeQxJ+xovUq2PhpWClWVBCICYHt1aD1qm6IKEii515E75iRRclfdcpeWBdcyWo93ajK3rnyj+yIPoSshc77glmPWgblfrlnjXe8Eek28F65sbrF0mxONvm9AV2mOnrMguuLj84Eu8o50zUMwlQuHA9sMgxKCexdqmHic6piX1deaKamXUAUJEO5+KwHohZRcRx5XKqP16jCWWnNf2orKq/v1ZnnZaMLQsuAyBBoF393F7mQy8wg8Ax65wVGIxP36TavmSk1vikuJRckqJ5dlEIC2I5IL90eGyfXKj9H1ARV6Dn0+Q70zlZXqYXQeJ40uQ1QNCWhCBkB4ISVLXoJaIM/WMlGzu7s7p5xu0anA6iqX4rDIra0BOWeknJEAIKXpt1lpnTtQmibMfVHniNxoJ0v1oBizMm/B/6VE3GHLktfgnRpYnNug20pk6sOyep0+LyYKK1y+OiTo8DL0QkqohgRKwtsvnDE1bleooiu5RDGWu7SR1e9yIQ8Lfv2qfIkEEJSPFNrrcVmwzmhpeJeR1q3Lb+s98nn0isgLOV9QYtTfJdmUPBrNk7CMZ+qj3I0jype418x9eoyGW22oigSUISMlcLe2DREB6PE+xz3q9FoX69Opx5FH0Kdt5wMuGw9lAIRZ/pJCuhWjVdSy7v5GIQS3s/NznHwymczkXjrvsuFkoPDwVI2E3wudlen5A96D6No1xOrSLSdebVNXaFoVCbggvGOpNWhTlLYOHcVyvCGlTDhQnv+uQl42EfC8mn0H4pGPSLZah9YDzL+x2b0An/3Gb50sFLnVAObyLSrjCIfpDbBN6tm4DJkw1dmTKqOc89yThapTqjO8Nv0fXa/va/O6Ig+vhCpIoOQCdaHLJfJyJdZ1D0SFG2WwWVfb/2VDLZhbtIgYfZLT7u7eEuQsE8W0+rixn9uJwZdd47kicl22LKkrnqviPv2tORDmPY4fP74QLqnsoqS3k4yfz/WVaCPSPl5VFSQALHairsZ72S6FiRI92tF16M+HAEvj/n7OWggAaM9tRGRYCsd8nyp0znm20KZ3ev8oMTAU8FGVKNSqBa5rkbfKNnMkhHqmb2TSV5ITmhvR2Yql80dGjEYq8jC6+lI1JBC5il1Qi+1oszTKwBy71seB9e3CvuDFsi1UCW0eUFsZYJ5wI6/ILZS6tv4gkecHPGziMe5l+crENclYO72OpKgx8XwT5aIzN300xI+LzstvlQf1PRqK9ON8X4QqSIAuU9ccZ4XP6oush7pp6tK79eHxPhEougk1KWcJbqlcYbUc5UAFJaL8jG/3vAAwf1+cfKOJVG0fraMGtIUICnX53UvysAzozm/5Q1ee7OY90MeWeRy937ZzVEECwGKcAyw+HKRC0/KcmqlKp+UJVXpPpDiB+NRNKoCTQU25AO38ngD1cv6/1H4nDUUUNpRyM1HcH3kOpXqXIWMnU7YjctU1xNK3EPN167u7u3NPp6ouqQxUn5ws9ByEhhxcyZly5vyXLi+7GhLwGCuKfbx8ZHX0Zqkbq0KN3FxVMN40JQsgfqlJLXDlKbnyXh6Yd+/ZObuIIfKM9Dyl4112UU5C79Oy4Z02crv52y07J+rQKq+srMxyA7rQjRIi/xPqNbm+a1jgiV2d6j4YEgDmL8wVFJhnT82ocl9kjVzJ9DgyMwXMoTSdXEFX2b2CmsnA4d5BlNTaT/1KFp6XieSkYZh+89y0Yhqa9BkdOmz0JSU1HPzPBOrKysrs5a6aJ2irW2WrOQVu034BLN6jwZCAT77gNoVbqJz3llUqxZWegaYCutAj99lJJBohIGoggpL1dC8h2k50Ha/elpcB5hVWScCTgiynMe3Zs3uvOyt5gMtAX/nof14DLbF2XJ9gpcOxbbP7KHeP8VWWLKf5gMHkBIByhlsfqtBy2qGjhJMO//lv1uNJQh3m8aWzPW9Qmxfg4PW15VrcK2gjuSgE0PqcJFW2nB3YNhegbcZorSgRosvRDcpBPUnv0DzWp76rrnbJshoSKAlTXR1dfAGY9xSY3fehKB+O8iErMmZp9ECHrlS5a+/8tALuPelYvXc4ylDj1cid9BDL3dEI2o5o2FAVtlZybQu1SqCMoklVrJP654vq+Pl0xMGP198lb7eEakiglPwjSuzKb1eqyHV3hY/GpVXpPdlyUPY+THj7tLNHs/xKr8BSeWioRrAezQn40JWPY0deWOkBr9qgltzR5rko4fo7MzThp3MPPL/lhBvlvgCE8uzjVVVDAsBiBtZJQBXNyaBEAO4W6U1x5VbFpXulb0LiubRNtUJlGE0A6qNQ0Us1fOpxFOcrefqEmtI9q51cgcWhar+mCLymyKBp/sTvkc6bcY8tivV1G1dvYv2DWWMwcvN9ZIAKFVkO7ndL4zEqy+ry4H6cl/f2ldo/BAVu21aKbUmWqliRVffO4Tmcrs6i5xwKeK2uSxFZujwJf9GIErd6cTyfIwrXcs6zPExpMROiFwmklE4C+CCAlwLIAH4LwP0APgHgBQC+C+BNOecn0vRstwB4A4BnALw15/zFjvrn3hHA9wO4ANrcMb14HfdXBfWOrtYqilVLmdooJFk23KIT3j7vZBERRJ6Y16FK7+FEiYDV8rtXFiXLapFtXzhhasfVju9D1bTe/gKSSP/9fPyOwgcOgXsuzdF3wv4tAD6Tc34xgJcBuA/AewDcnXO+GsDdzX8AeD2Aq5vPTQBu7XMCxkw6BVWTcopSzMR6ogxzFEZ4XdyvsZUex+8+cdYy0CaXqENpZ9/v9bC8jn2vr6/PvV16e3t7bk1BXaFJ42R/PfdBYu9loBQaRgYlCn2ARb0vfTsxRATLXM5+72unJ5BSuhjAzwN4a3OBWwC2UkrXA3h1U+wjAP4VwB8AuB7AR/P0Kv89pXQypXRZzvmRtvMoc6pXwIuR9ixY/qDNC2yrGdUoKx1ZoKHE/0A8lt1HAfp2qog46bp6wqtt7gYw/1IS/uc8Af1dU4dv84r02iPXX71KtezeyTUP4B25ROzeB9RoaljQhj7hwFUAHgPw4ZTSywDcC+BdAC6Vjv0ogEub35cDOCXHP9RsmyOBlNJNmHoKOH78+Jy116mjur0Ur/s+VTYVEt00Hw4sEUApN1A7IRClUKDN5e7b8UpeBhWTyqxPCaq8o3NFit52PcuGEkC0T71KXpP+BxY9Vx9R0d8ub+qi6mRcJx6yAAAeIUlEQVSUoO0afelDAisAXgHgHTnne1JKt2DP9WejckppX3co53wbgNsA4LnPfW7mRbHxTZnZd8Sw/sipKlkkVJ7DcwLeGUr/hxKrqtw0SUW4YrZ5Dk6M9K50uy64onJV5dZ26HkZs/riLbWjRAAqB3XPef2aM9DO7NadvwnNKZRCJfU8eHzpRaWKPiTwEICHcs73NP/vwJQEvkc3P6V0GYDvN/sfBnClHH9Fs60XuhRR/0eWW8nBh1GiSUQlhWs7B3/XhpKF9TJ+3VQ8XfCiTx0Kn6Di05MVrvSsT2dp9rmWw4R3zsiL8fLacfW/x/Ru3Fx2EVG3GbnShKQSOkkg5/xoSulUSulFOef7AVwH4OvN5wYAf9p8f7o55E4Av5NSuh3AzwJ4MnfkA7ShbdZfL0QvVveRZXWcW8+h+5wMPE/AY/S7drQpp8vSydKHt0rHegil5ajo+uSl5mCidih5R5OOSqHHYaPN+gOL8wh0f6TDfu1t7r/K2j1lHz3bL3H2nSfwDgAfTymtAfg2gLdhOrLwtymlGwH8D4A3NWX/EdPhwQcwHSJ8W58TOGtGAnMXyp+mokKvrq4CwIJrqfmA6G2ukYKXWLS23ICPKwPtSqHWSK2PJ5V8v8tTz6PblXD1N++Bv+RFz8XzqLXrsmaHBSUyDbMiAiht04TgucBD2y7vrYReJJBz/jKAa4Jd1wVlM4C396nXjitmhL2Dcpu6+e7iqtsV1cfvyAsoDevUiqjTtyXutCww/zJYLdNGhtF9UJSOU4sf3VPfpte4bG/A9SvyhLivdAxJgKFXNFTqdRBO9BEBHSR8qmbGYOmmR25pqYNqEipSJi9H91ctlFqnocxr3w+UMHSaKSeqRLKO4vu+yqbn09Aj6ujsFNF9qpmEFSViAPa8V8pbP9E8CfeMea/aZg/6+fS7hGpIAFhUsIhhNYbSBR0pYFcili9ZKyeBUgxbO/ZrAdQtdQU8l3q9fu0QnhAjwbAdnPMOLCbiSsRx2GizttzXRgI+EYgEEM3v9/8e7vGcETyZ2HYfqyGByG3ib02A+PwBhhHA3sorypi+hgA9BV1RWIemSkItucM1Ibrxak31t350gop/PHYtJQujtvi3kgDBe8W1+FhW70lfi1YLumTi/6NOrcYrkrmX71t/hKpIoK2xqsB6jFvynPNcrMX/VEBOWonOH/0eGkoWKCIAtUSRG+pkESlVKflVKscHt3LOM1d4d3d3rh2TyQSbm5tzz25o24Z6f6KcU1vOhSTsoUFJBlGo1oc4qyGBroeEFOpWUSg+xXh7e3suP6A5AO8MJArWEeUBInavRRldZpFF9+1KBFEHj+pgeaD92v28LF9KLHpilvfL9cDDvBoQ6UQp9PRQyI0XUSLRPv3CZd9HTlWRQNuNVyVSZYjeiEuLz6cRCbqZ/K3HEz7DThVOb2ANiFx9JTy34t4pXVFKSuZ1uTJHdTucALQjlIZs9Rrb2rcM6PWUhkpZTmcL6kfnsTDvQZTCsxI8qajn7yKCKkhAFdk7XNQB+UlpOsuNdfDiGfNPJhNsbW2FC12qtWmznKX21IbIakeuvCZWddEQwuN1DRs8KQWU13bwNrGs5l787UNuDUuKvSxEHbyrXao3Pj1aoV6te61q3NwLoiGjMVPddqNZQhUkULIcpRl8TgL+9NXu7i5WV1dnLyWhV7C5uTl73Rjr9AktkaWvteN3IQoFAMw8JSqQu99RB/SOyKRrpJT+7b8nkwnSZAKkxemzeqz/5v9a70fkiutv6pa+C8ANoBNtJHc/Z3TuqEwJVZCAwi+SnT3yCtTVihSDJME6KXx9gjBafLQ0gWgIUKVSqCXxbToXIFJkPooavV1X70lEAFonz7Nz9iyOiawnQuoa0uzHmi0DUefSjhx1Sh3eprUnmeoMWA+3dBvPrcOmlG10zkGQQEppthiFX7BabH0uWlcJVsvmbq93aN0fTQzyRBX385ghoM0iaSfWpCCv0WcOqoxzznPH6KSVkmxUkSOS9YSg7oueJeA11HgvnGRLnc+vVz1bYG+9BSUEEgVloaQNLL51ez9hVDUksLa2tpAX4D5gKojNzc3ZNlp0jfUV++nAbYKqUdn6wj0lKqkPDxLa2fxeaAhFBVSvTY91JWcIFs7OLCwDHz3lOeR74fka9W7d6qvnGfUHn9vh5/HfkWeoqIYEusahAWB1dXXOM1B3ittUoDrtVy0//0fhBc+pbalZ+aKYWy1qlHBV+H+1SKX74vcAWHx02EdlKP/S+x88/PJ7ovUsC37uNktf2qcelJZ3EtVrdctecvt5bFend1RBAm2gcFR5XCCR0kTu1tbW1twwFMtFFqdvp1kmSkqhVl+VoWu4tC0JxZi1T8ypLiqTtisrKzPZ7+zsYHNzc2HF4qjjR/Vz27LvhYeXUb7F74kaLfdoNYcVkSuPceLX7TyXlu+SU1UkoJbYOzHHkbVzegyl7pTfEO/83B4JKCIU/a4BJWVw+LVQRvrEptbF5JR+NH8QZa+j+ezqlei90eP6XBu9vVrhIZfv0/1RboPflDMArKysdHbyKGTW9ugxJT0nqiABjem1sdF7AEsuvM8g1Lo9NIjOT7QlrYYIVQoNDXTMnkpX8igI9wL8GN2vL2+h7Hd2dmbzNtQL0Lr4iUhDlbpmqDuvpEvPyI2dkgDloB6Bbo/ugX5H6AoNqiCB3d1dbGxszCls1NkjIgDmY1Uqt85A8wyz11mKTWseFfAb2xaH+jFunXks3fau2DOy+q7YWtaJtBTPembb76+ftya0hY2UkYau0agHicBJW2WiD8i1vVlIcw+DSAzmvJf5j6w9f7tF92E/tTTRyECXa1XyOIYI7chdjwq7FY6Ur0vZ1B2OnsrsI9MoLzBU+Sv6eC9tll7vh95PJ4HoHF2GAaiEBIDFISZ+a6f07DK3U8icFVh6+sxjMN0ehQpDcD3bQMvR9yEhP7Yr5xCFC+55lTL+keX0+Rq6r0a0eV+e12jr2MBeOLu6urowFyN6J2Fk3dvuYfWegMJdQU/6qUvkVmZ3d3f2LEGUhKEgdJw8SqTwxpReQ1YD+iqgKpLCrQrrdHLU80V1R/LT+QdRp448sShEi7bXRgjuZbZt93viz2boKkPROwl1gpD3iRK69gMVkgDhVptQhSWoJBQmX3ulndiVh8pK6xNZx5rhHUS9G8IVTrdHr7mKknxR5p91aPJKScbPxenaHjbwd3SfovtbGwGU0Mf157daf38foecC3ED6+fTeeB1tqIYEogST/4/cKkLHpFUJ/alBR+2dvQ2lzlHyBNQT8jjTPQPv+Exa8T/hs9dcISeTyexhLrXuPtuQw2jRCAW/hx6eOVxWrvtRDsCPjSa/Rfe3DVWRQATP1EcWm0qlREGh6AhBdE5PBA4J3lE9ZqTi6MddfmD+VfCelIveoafQ+vhfv/VYWjQ/B7PdbIvec/UcNM9QIyFEnpj+jsIg94JUzlHopceqrLRfeJku/a6CBPziHNGDJG6BgMWYi4pPQfi0YX4PcVTgXD0Y77wAZouw6NLXer6U9t6lB2D2qLYSThQb6xRmVXTt6Cyr98zDB62zRkTtKnlrvHY+FKcxPi0/9VL1VvMB/Djxa11qQEuoggQiBVOoALVDM5ZX9zXn6SgBcwLKotHQFc9bewLKUQpvvIzmPNzdVFBRzp49O/dwkcf9Og3Y6/AYVC0drX1p0hfbFQ1VOtEPBZHl1nkA3Kf5HN6vyWQyp+Ner3oAkby08/uCLY5qSMCz/aVyBF39yLXVGWmeYHIljEjAP0OEKh47omacNXzQ8vpbM9e+TLau09Dmvup9US+M7SrNJ/C6aoV34ig00k6vjwTrdfOtWWrlqceug3oekqsvFls6f4QqSACYf2e9TxlVluT+KC7yDh91YI1rI+UbiifgIVAEtcTqMnIfsLi2o1t9tyo8Xi2Rx6TeJidol3M0pyCaN6L11ZQTUDmUXH9gz+DQ0qvMSgZLvVlgcb3HKJGrbepDotWRgM9u81BAFxaJOnBkxfW3Wz9djGRIXkCpo7kF1Q6oZdx6R50/SmTt7k7XB2h7V4ETjh6v+ZqSZ+b33g1Cjfcm0jUikiG3d5GZe2WlB7m0Xpf19vZ2/eEAsDdmqogmR2h5hcY96iEow0ZxZeR5uDtVG7zjEt6Ro+E2TSTp0JwqqN8LP5fX46SibdR7wnpTSnMTY/icB7A31Mt2RRau1vsCLMpGt7uM1br7dTph+zsigPJsTB812NzcHA4JuEUG5gXk4/8qIHoJvsCIZ1fdjfV4SYVVKxlEXkBEcH3iau2kPhwYJem03mhIUst6h9Vy3L+6uoqtra3ZG4icwDU+1vbWiJIHwH28NnpBnmztc688r+KdXmXGNpReuENURwJURnf73OqoxVKh0vVx6+dCikigZGVqij8JvUbd5p+Sq67l1eq6l1SaaORuqXdwYH7atXsMSvI6LBjVOzR4jkDzKNRdnTfRNZlHvYcoBNYEonu+kZfhqIYESvDEliquZ5bpVuoQoXoHnl/wvMFQ5gqUCIDfUdwcWW8vr/ItxbZq7f1dBEoyTryqmG7ZNRPuD4hFBqH2kMDhRsmv2cM6P9ZDL93Xdb+PHTsWDjMqqiGBKJ7xCRGEK40qDAmAZOC5Ao+d9Pzentrh8TbQ/uyDWnCvo61+PxfP454a90euvIdnGrZtbm5ia2tr9l4Iv3/ROHeN3hkRyd6JO+e9pDRJgLLRnIjra3R/1TvW8zOPUGoTURUJlJRHL04Fou4u90es2mbZh2pdCLqbUcf3EMDj8ZLsNE7V85RiXk8a+seJWjv22bNnZwTAdQd1URgnAPUIhwK/B57/ivQ+0uUopPO8lZ5jMpnMLc5bQlUk4KynLr+W47cqIZmTjwdzv64wRKS0t9wT6/LQYsiIXMMoaaf7+K0EUIonPZnqQ7pRiOWZbN5fJgVp/Xmv/IGjIaLkofljwkoGSgCe/NZ6+Jvfeg+1XnoTbehFAimldwP4bQAZwFcBvA3AZQBuB/B8APcC+I2c81ZKaR3ARwH8NIDHAfxqzvm7Pc6x4OJEKF2QMq0SgSpR26SiiGhqRdRedzWBxeElvuBF0aZAimhhCz2XtitKtrrCMlYtkT/LRtcexcY1ge1xq6+yLRGBP1CkhOqPffvwMLDYj/x+RGhPS04rvRzAOwFck3N+KYBjAN4M4P0Abs45vxDAEwBubA65EcATzfabm3KtYHzkKwdJGxbYz9o4V8bHVXWKa20Kc1C0hThE5OJ7Yi96lyOPBfaIE5hf8660EIaTiJ7Pnz3gObvqKoV3ep01Iro3JdJleea1tra2sLGxgY2NDZw5cwZnzpzBxsbGLG+iRBl5b56IbNOTvuHACoALUkrbAE4AeATAawD8WrP/IwD+CMCtAK5vfgPAHQD+MqWUckfv29raap3g47+JUryo7NsWN5fq8nqHALK+rmjrMSdlUjqWyuWvzSbU4nhoAWDhCTiFDo3R3dU586xXl5dXL85jaW37MrEfnVKZOAFoOQ+lnIwBzJE3gIVyfdFJAjnnh1NKHwDwIIAzAP4JU/f/hzlnzuF9CMDlze/LAZxqjt1JKT2JacjwA603pXQTgJsAYH19HZPJZCF+58WqoPSCo/UGCRVIxIRRAovbny2gAjEHAsyP8/u1Ul46iqDy9iSV/o5kGCWtVN5R6FYK2aJzH0Thzwc8HNPt/Nb8E+EGa3V1daGeUu6mzeKr/PoYsE4SSCldgql1vwrADwF8EsDrOmvuQM75NgC3AcBznvOcDMyvEdCcO1Q2YKoAOh9AYykKKBqi6soHDB3qrrtrTncz8nI0OUXZ6QiBe2dtOZvIXS/dC7qzkQL7HITouZGa14EE5nMiqrvAdP0GD2X5Ts4ohPInOiNvIQrfunICfcKB1wL4Ts75MQBIKX0KwKsAnEwprTTewBUAHm7KPwzgSgAPpZRWAFyMaYKwFeqmqtJGLmkpY+ruoyebSoxNDJkMKAOuWbe6ujr3yK9edynr7wqp1ot1q2cREXbkcfnEIP1me6JFTDiRJiIJ6kpkYZcJ7fAuzwi6T19QEuVYvL5suTQP27rOTfQhgQcBXJtSOoFpOHAdgC8A+DyAN2I6QnADgE835e9s/v9bs/9zXfkAYHEMNOqw6l7RfaKQorcV+RBjW3LRz9G1bdmIciVRwo6LWPo1u5L4ft/nbid/R+1pC798G7/dtY8IPCpTAyIX3/9HuhzJ18kxGq0hsVI26iF5P+pDBH1yAveklO4A8EUAOwC+hKkb/w8Abk8p/Umz7UPNIR8C8LGU0gMA/hfTkYROeMIquuGRWxMJN4otGXvqyx8jyzUEsO2ehY8IoEQCbZ3cM8/uUUSehHtgul0tVaTMPmXYybxEPG2d77DhBkrDK273iVq8Lp+UxfUGtDzropyclDVXEI0StKHX6EDO+X0A3mebvw3gZ4KyGwB+pU+9RKRYdDmjWFHOtaAoEQFEyq5KUzsRdLmTGgqUFKFkFSJvQMOyaNiuVFfUQT3u123a6TVX4DGxTx13XVg2AZTgMoo8KuqrEwFzXSp7zQdoWQ+ndIJQH7lUM2OQwqHVUhdQ9+vFqbtIRC6mln02zQwk1JWktVALoqvTKOG6kjp5KKkA3aFAKc9AOJlre3SUQIcHnRQ4/FhqS02gDHU+RJdl9inyThrqxbJcROw8pg9BVkMCrlSe4efF+PJU7jby+MjFdYujrutQiEFvvmfP1QXVufrqitJKuIzUnfTf7r6qokYE0CVHV2Y9D4eIOVyszxBEHaB2IiBcTt5uD3VLnd/vCbe1rTp0zjmBwwCH+/SNuGoF1E3kHPMoVlTmpDC6QobassttKIU1rgzRLDuvxzu61xW5+qqY/pBLXzJVQuY90Me/vfNzW0kWNYNy0v9u6fW3ylBHP6IRgmgYkXkbnwFaGg0iqiCBzc1NnDp1ChdeeCFOnDiBtbW1GSGo0Og2AvMrC2kiSUcDGCepWxyhaxy1JkQdNeq0ajXdghJUSh+ajfIIUWgALA43ukL7+fjNc/NN0nyIKPLunOCHQgD8jvICkbeqFt+NlYdxvB+aK1BvQMM69pkSqiCBnZ0dPPjgg1hdXcX6+jouuuginDx5EhdccAGA+UlEFIi+R1CnqXLmobu8JQsH1JtYUpTiPlcitTZENDtQj6GiRYuE8Fs9DbdiUSgQEY57b54LSCnNZb81HBwSUXto6x1ZoTrN/1FCN0r4+mQiD+XaRnMUVZAAgJk7eObMGZw+fRqPP/44jh8/jslkguPHj+Oiiy6ac3f85Rca73oY4IgUuHYSALrnObi3EymSW2l1zz13oFaJBKvkWmpLH0udUppNaOI3vQF+SEzRbM8hwHMpUYjmngIRhWve+fV++rRu1q15oRKqIQGCMeLOzg7OnDkz5/5QYU6cODELG+gVtHV8V6C2TlEbSh2q5NUA8xlmYJ7gVFGooPrUpoZhbcShoZaeq0QOUW6GbfUwLcpzRMPFNd83IiLcyDPzEMDDLv2tycFoFC2lNPc04unTp8O8ClEdCSj0RnMFmpQSnn766Zkruba2hhMnTmB9fT2Mi30JMvcC2jrTEBDFldq5VX60RlREVSYerxNVgL1hx2iKdhSiuPvpsa5u84lCPved51fvYwgdX6Fy8tmAUTnPmyh0CJjH62PyXKFpd3cXGxsbeOqpp3D69Gk888wz2NzcLLaxahKIoMqzvb2NjY2NGSloltRf6xRZkaEoVJRYKv1XaOfz8XVVQv7mNwlDx7XdIpUSX8D8W4PZyb0Obb+GcbpyNL9LCclSuFczlJxL8wZK4areT33XJoDZugMbGxszD8CTrCUMjgQcblGAeAaij3tToENRJE/S6TZHKTmndWmGuVSnJgI9RnUi4LFaX1RGy/Ec0dg2j9EVeDTh63Lxc9SMknfk+9Vj8tmUXGhka2trpvsHfbZi8CSgUIWLJl9Q8bUsfw9BgTyEiUIa7yRRlthjbtat0Ni063x+nLeZIwA68cvd+4hk/BwRYQ3hvjkB6rZIDzlvhnNnAMyGUTUH0MeA9ZHPs4oE2hCFACVFrhV9Q4HIckfb2uDyis7l+YFSWyKF53+d3+FLjft7CErLjw8JniMA5qd9R/kc7usTxh7EMzoyJEAcxF2qAd4ZfUaZlmG50tt82jyHiDD84ZUo3Gpz/9lOtV767R0+yt24yxt1hqF4BkAcEnj8Hx3Tp9794siRwLMBXVbcy7YRgFpx7fja+TmOX3qKUJVZlZvwvI0OSXq7tB3ezhLB8PghEUDb/8PGSAIDQdSZ+xwTxfRAPIPPSaAtdHBXVVcP8jYA89l8j2Xbcg6sc0jPeAwNIwkMAGoBabnVje+y4CUr65acdfE7csu9DW2ZfWAvMclQYHV1dfamIY19tS5dxozt5dBhifxGcjg4RhKoHFEiiR1GE3Msp6sKra2tLcTxwPwQnUKHoTRZ56sUtdXnnZEdmFhbW8Pa2hq2t7dn7yDUa9LRm+iRZbbTRxeic4/oh5EEBgJPJKkFjmb0cVydYCf1Nwn5OfyBnZTSXMKOU7VLIYPWAWBuJego9PBOzzJcMJV1+IxPDydGAjg4RhIYCKLxZF8xSEcEfE1AnVHp4QAQT/n1EQZ6Az7iwP9sY0QCTgC6T0cIOD4erTXAbTp8Nnb+fmgjypEEBoC24SLft729HdbhHd6PZYfmKABRSix63Z5LINSKe52e8Ms5h4uIjFb/3NEms5EEjgi6hqX4/yAv8yiNHkRkc64YCeBHj5EEjiB+1B2pVN/YYYeBzrcSjxgx4tmNkQRGjDjiGElgxIgjjpEERow44hhJYMSII46RBEaMOOIYSWDEiCOOkQRGjDjiGElgxIgjjpEERow44hhJYMSII46RBEaMOOIYSWDEiCOOkQRGjDjiGElgxIgjjpEERow44qhlUZGnAdy/7EbsAz8G4AfLbkRPDKmtwLDaO6S2AsBPRBtrIYH7c87XLLsRfZFS+sJQ2juktgLDau+Q2tqGMRwYMeKIYySBESOOOGohgduW3YB9YkjtHVJbgWG1d0htLSKNK8KOGHG0UYsnMGLEiCVhJIERI444lk4CKaXXpZTuTyk9kFJ6TwXtuTKl9PmU0tdTSv+VUnpXs/15KaV/Til9s/m+pNmeUkp/0bT/KymlVyyhzcdSSl9KKd3V/L8qpXRP06ZPpJTWmu3rzf8Hmv0vWEJbT6aU7kgpfSOldF9K6ZW1yjal9O5GB76WUvqblNLxmmV7UCyVBFJKxwD8FYDXA3gJgLeklF6yzDYB2AHweznnlwC4FsDbmza9B8DdOeerAdzd/Aembb+6+dwE4NbDbzLeBeA++f9+ADfnnF8I4AkANzbbbwTwRLP95qbcYeMWAJ/JOb8YwMswbXd1sk0pXQ7gnQCuyTm/FMAxAG9G3bI9GPgiyGV8ALwSwGfl/3sBvHeZbQra+GkAv4DpjMbLmm2XYTrBCQD+GsBbpPys3CG17wpMO85rANwFIGE6i23FZQzgswBe2fxeacqlQ2zrxQC+4+esUbYALgdwCsDzGlndBeAXa5XtuXyWHQ5Q0MRDzbYq0Lh0LwdwD4BLc86PNLseBXBp83vZ1/DnAH4fwG7z//kAfphz5qt9tT2ztjb7n2zKHxauAvAYgA834csHU0oXokLZ5pwfBvABAA8CeARTWd2LemV7YCybBKpFSukiAH8H4Hdzzk/pvjyl+6WPraaUfgnA93PO9y67LT2xAuAVAG7NOb8cwP9hz/UHUJVsLwFwPabE9eMALgTwuqU26jxh2STwMIAr5f8VzbalIqW0iikBfDzn/Klm8/dSSpc1+y8D8P1m+zKv4VUAfjml9F0At2MaEtwC4GRKic+FaHtmbW32Xwzg8UNqKzC1nA/lnO9p/t+BKSnUKNvXAvhOzvmxnPM2gE9hKu9aZXtgLJsE/hPA1U3GdQ3TxMudy2xQSikB+BCA+3LOfya77gRwQ/P7BkxzBdz+m00m+1oAT4pre16Rc35vzvmKnPMLMJXd53LOvw7g8wDeWGgrr+GNTflDs7o550cBnEopvajZdB2Ar6NC2WIaBlybUjrR6ATbWqVszwnLTkoAeAOA/wbwLQB/WEF7fg5Td/QrAL7cfN6AaXx3N4BvAvgXAM9ryidMRzi+BeCrmGaTl9HuVwO4q/n9kwD+A8ADAD4JYL3Zfrz5/0Cz/yeX0M6fAvCFRr5/D+CSWmUL4I8BfAPA1wB8DMB6zbI96GecNjxixBHHssOBESNGLBkjCYwYccQxksCIEUccIwmMGHHEMZLAiBFHHCMJjBhxxDGSwIgRRxz/D885U4iY6f+BAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "\n",
    "plt.imshow(img[10].astype(int))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
